### ISSUE TITLE
Add JDK 11 to sdkman

### ISSUE THREAD

**Issue by parttimenerd** [SAP/SapMachine#1011]
I'm missing the SapMachine builds for version 11 in sdkman, maybe we could add it somehow.

**Comment by RealCLanger** [comment]
I think that's rather an issue for the [SDKMAN](https://github.com/sdkman) project, isn't it?

**Comment by parttimenerd** [comment]
On the first glance, it looked as if the SapMaschine team is a vendor to sdkman and therefore should have some semi-automated way of adding new SDK versions (https://sdkman.io/vendors).

**Comment by parttimenerd** [comment]
I did not find any pull requests or issues related to SapMaschine in the sdkman repository.

**Comment by parttimenerd** [comment]
Maybe it is related to https://github.com/sdkman/sdkman-db-migrations/issues/496

**Comment by parttimenerd** [comment]
SapMaschine just does not have a Mac M1 build of version 11 in SDKMan and does not build it at all. I'm going to close this issue and probably open another that is more specific to the actual problem.
