### ISSUE TITLE
SAP Closes Unexpectedly 

### ISSUE THREAD

**Issue by burakard** [SAP/SapMachine#1013]
After I make some operations, SAP suddenly shuts down. After it's shut down I am faced with an error report like this.

By the way I use MAC
[Hata.txt](https://github.com/SAP/SapMachine/files/7870603/Hata.txt)
.

**Comment by RealCLanger** [comment]
This seems to be a SAP GUI issue. @woersi can you check this and guide @burakard...?

**Comment by RealCLanger** [comment]
ref https://github.com/SAP/SapMachine/issues/991#issuecomment-975287446

**Comment by woersi** [comment]
It seems you are using SAPGUI for Java 7.50 rev 13  on macOS Monterey 12.0.1. That version has never been tested on Monterey. (In general we usually do not test outdated versions on new OS versions, only the latest.)
Support for Monterey starts with SAPGUI for Java 7.70 rev 4. Please refer to https://launchpad.support.sap.com/#/notes/2983405

In case there are still  issues, please report them to SAP Support on component BC-FES-JAV, which is our official support channel.

**Comment by RealCLanger** [comment]
Thanks @woersi. I'm closing this issue then.
