### ISSUE TITLE
The items won't be clicked on MM01 screen

### ISSUE THREAD

**Issue by burakard** [SAP/SapMachine#1014]
When I click on material view at MM01 transaction code, I cannot choose the items. That is, when I click on an item it is not chosen but when I click on the second item the first one is chosen.
How can I fix this problem?
I use MACOS Monterey 12.1 version and SAP GUI 770 rev4. I am uploading the video record of the error.

https://user-images.githubusercontent.com/95231862/149542707-fd999b1b-d2ba-43c7-b9f5-1ca4cb22add8.mov

**Comment by RealCLanger** [comment]
@burakard, can you please open a ticket with SAP Support on component BC-FES-JAV? This is again about SAP GUI for Java and that would be the official support channel.

Thanks for your understanding.

**Comment by burakard** [comment]
Thank you @RealCLanger
