### ISSUE TITLE
Chocolatey packages

### ISSUE THREAD

**Issue by johanjanssen** [SAP/SapMachine#1016]
Chocolatey is a package manager for Windows. I maintain several SapMachine packages for Chocolatey: https://community.chocolatey.org/packages/sapmachine. 

The complete list/configuration can be found here: https://github.com/johanjanssen/ChocolateyPackages

Maybe it's good to list this option in your manual as part of the installation options for Windows.

I also noticed you're managing the Homebrew packages yourself. If you're interested, I would be willing to hand over the Chocolatey packages and configuration if you want.

**Comment by RealCLanger** [comment]
Hi @johanjanssen,

thanks for bringing this to our attention.

I guess the logical place to refer to Chocolatey installation would be this: https://github.com/SAP/SapMachine/wiki/Installation. 

Can you write a suggestion for the text we should add there? I can then update the Wiki with it.

We don't want to take ownership of the packages, though. But if you have a simple mechanism for version bumps, e.g. like `brew --bump-cask-pr`, we can consider doing this as part of our release process.

Best regards
Christoph

**Comment by RealCLanger** [comment]
Closing this ticket as I didn't hear back. But feel free to contact me with a suggestion for adding to our installation Wiki.
