### ISSUE TITLE
How to make SapMachine JVM 17 release memory back to OS eagerly

### ISSUE THREAD

**Issue by pandagodyyy** [SAP/SapMachine#1023]
Hi,
I am the internal developer from SAP.
I use SapMachine JVM 17 for the java services in Kubernetes, in order to for better memory resource usage, I enable the autoscaling for the Java services.
I found it is successful for java services to scale out because JVM requires more memory than expected. but it is hard for java services to scale down even the memory in use become  low. It is because the JVM is not eagerly to give back allocated memory to OS. so the autoscaling cannot not react. 

I do not want to programmatically call System.gc(). I hope the JVM can behave aggressively to give back memory to OS so that the autoscaling can perform well. Do you have some suggestion or  recommendation to configure the JVM to reach my requirement?

Regards,
George Qiao

**Comment by tstuefe** [comment]
Sorry, this is a very unspecific question. What exactly is your application doing? Why do you think it uses too much memory? What memory, java heap or native? What GC are you using, what options do you start the VM with?

Cheers, Thomas

**Comment by RealCLanger** [comment]
Closing this issue as the discussion continued SAP internally.
