### ISSUE TITLE
Standardize `sapmachine_releases.json` for osx

### ISSUE THREAD

**Issue by eddumelendez** [SAP/SapMachine#1024]
Context:
There is currently a [project](https://github.com/eddumelendez/sdkman-java-migrations/blob/master/README.md?plain=1#L33-L35) which use the `sapmachine_releases.json` file to publish new versions to `sdkman`.

Problem:
Nowadays, the file doesn't offer `tar.gz` for `osx-x64` and `osx-aarch64`. Version 18 seems to provide `tar.gz` only for `osx-aarch64`.

Suggestion:
Windows offers `windows-x64-installer` for `msi` and `windows-x64` for `zip`. Based on that, my proposal is to have `osx-x64-installer` and `osx-aarch64-installer` containing the `dmg` and use `osx-x64` and `osx-aarch64` containing the `tar.gz`

**Comment by RealCLanger** [comment]
Hi @eddumelendez,

thanks for bringing this to our attention. I think it makes sense to update this in the way you suggest. We use this json to fill the download box on https://sapmachine.io/ but this fits there as well.

Please bear with us for a while, I'll notify you here when it's updated.

Cheers
Christoph

**Comment by RealCLanger** [comment]
I've implemented your suggestions. Please check https://github.com/SAP/SapMachine/blob/gh-pages/assets/data/sapmachine_releases.json and let me know if this is what you need or if you still see issues.

**Comment by eddumelendez** [comment]
thank you so much @RealCLanger !
