### ISSUE TITLE
"Expecting a stackmap frame at branch target 19" when using AspectJ Weaving

### ISSUE THREAD

**Issue by fabiofilpi** [SAP/SapMachine#1045]
When using AOP, configured as described at https://help.sap.com/viewer/d0224eca81e249cb821f2cdf45a82ace/2105/en-US/8c62d88286691014874bc5b8e7244c7a.html, I am receiving an Exception with Localized Message: "Expecting a stackmap frame at branch target 19\nException Details:\n  Location:\n    br/com/vivo/deliveryservices/aspect/ZoneDeliveryModeAspect.aspectOf()Lbr/com/vivo/deliveryservices/aspect/ZoneDeliveryModeAspect; @3: ifnonnull\n  Reason:\n    Expected stackmap frame at this location.\n  Bytecode:\n    0000000: b200 6dc7 0010 bb00 6f59 1271 b200 73b7\n    0000010: 0076 bfb2 006d b0                      \n"

I am not finding infos about it when using SAP JDK

**Comment by MSailer** [comment]
Hey Fábio,

thanks for getting in touch. At first sight, it doesn't look like an issue with SapMachine. Could you please share the complete log file?

**Comment by RealCLanger** [comment]
No response received, hence closing the issue. Feel free to reopen.
