### ISSUE TITLE
UseContainerSupport vm option does not work

### ISSUE THREAD

**Issue by kokmike** [SAP/SapMachine#1101]
Hello,

We are using SAP JVM 8 version 81.86.86 (or 81.81.81) in kubenetes cluster

cgroup memory limit shows 8 GB but JVM is still using 4 GB as maxRAM to calculate maxHeapSize.

We have added -XX:+UseContainerSupport but it seems that it does not take effect.

9679fb0c40d3:/usr/sap/sdc/sapjvm/bin # ./java -version
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 8.1.086)
SAP Java Server VM (build 8.1.086 11.0.14+000, Mar  9 2022 11:15:15 - 81_REL - optU - linux amd64 - 6 - bas2:332856 (mixed mode))
9679fb0c40d3:/usr/sap/sdc/sapjvm/bin # cat /sys/fs/cgroup/memory/memory.limit_in_bytes
8589934592
9679fb0c40d3:/usr/sap/sdc/sapjvm/bin # ./java -XX:MaxRAMPercentage=50 -XX:+UseContainerSupport -XX:+PrintFlagsFinal -version 2>&1 | grep -Ei "maxheapsize|maxram"
   size_t MaxHeapSize                              = 2147483648                                {product} {ergonomic}
 uint64_t MaxRAM                                   = 4294967296                             {pd product} {default}
    uintx MaxRAMFraction                           = 4                                         {product} {default}
   double MaxRAMPercentage                         = 50.000000                                 {product} {command line}

**Comment by RealCLanger** [comment]
Closing this issue as it is about SAP JVM and you have reached the right support channel for this meanwhile.
