### ISSUE TITLE
QUESTION about path enviroment variable separation

### ISSUE THREAD

**Issue by jokbon** [SAP/SapMachine#1110]
**Instaliation guide told me to:**
Set environment variable JAVA_HOME to the root directory of the extracted archive (e.g. /<...>/sapmachine-jdk-11.0.3)
Add $JAVA_HOME/bin to the environment variable PATH 

Question is **how to separate those variables**? I'am unsure how to add it to path properly, i fear of bricking my pc lol.
**I have this:**
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
**Do i need to do this?**
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin";"$JAVA_HOME/bin"

**Comment by jokbon** [comment]
Sorry windows user trying linux, so ya... somebody told me to use : for separation (what? lol thats not wery nice of linux :-1: ) would be nice to update sap instaliation totorial with information on how to separate those...

**Comment by jokbon** [comment]
hmm still not working it not finding java

**Comment by RealCLanger** [comment]
Hi @jokbon, can you share the link to the documentation that says exactly this: `Add $JAVA_HOME/bin to the environment variable PATH`?
Other than that, you should probably do both:
export JAVA_HOME=<path to your jdk>
export PATH=$PATH:<path to your jdk>/bin

HTH

**Comment by jokbon** [comment]
Trying to find more permament method tho. looks like i will have to do this for all 40 of my java scrips:
export JAVA_HOME=
export PATH=$PATH:/bin

Whats suprising, that adding this did not help:
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$JAVA_HOME/bin:$PATH"
(LOCATION IS: /etc/environment)

**Comment by jokbon** [comment]
https://github.com/SAP/SapMachine/wiki/Installation <----- This is documentation that says exactly this.

Found working workaround, i needed to set bash profile:
**File:**
.bash_profile
**Location:**
/home/[yourusername]/
**File content:**
cat > .bash_profile
export JAVA_HOME=$HOME/jdk-17.0.1.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH

**Comment by RealCLanger** [comment]
@jokbon Sorry for the late reply. I read through this again. Hope you could solve your problem, also with /etc/environment now. However, I don't see any point in getting more specific in our documentation cited above.
I'm going to close this ticket but feel free to post if you still need help setting your environment up for using SapMachine.
