### ISSUE TITLE
Docker images for Apple Silicon are not available

### ISSUE THREAD

**Issue by viktorsap** [SAP/SapMachine#1127]
Can you please make docker images for Apple Silicon available in the docker library?

**Comment by nice2mitja** [comment]
Hey there, we plan to have those available with the update in July.

**Comment by folz-a** [comment]
Any update regarding this?
My team uses M1 Macs and could use these images for local development.
We also have Intel Macs and Windows users.

**Comment by nice2mitja** [comment]
> Any update regarding this? My team uses M1 Macs and could use these images for local development. We also have Intel Macs and Windows users.

@folz-a: update will happen soonish, we are working on it :)

**Comment by folz-a** [comment]
Any update regarding this? 😉

**Comment by RealCLanger** [comment]
> Any update regarding this? 😉

Still working on this - I'm hoping it won't take too long until it's resolved. (In the range of some days to a very few weeks, hopefully)

**Comment by RealCLanger** [comment]
Finally, the images are available.

We've added arm64 and linuxppc64le to our [DockerHub images](https://hub.docker.com/_/sapmachine).

(See: https://github.com/docker-library/official-images/commit/f881ee15302b52387aee06629ee22c101bec4c21)
