### ISSUE TITLE
Installing SapMachine jvm debug symbols

### ISSUE THREAD

**Issue by holy-moly-555** [SAP/SapMachine#1130]
Hi there,

our application, running on sapmachine 11, shall be monitored with an APM Agent. For some features, this agent relies on the [jvm async-profiler](https://github.com/jvm-profiling-tools/async-profiler).

The profiler however requires one to have the jvm debug symbols installed. With openjdk runtimes, these can be easily installed through another package, e.g. the `openjdk-11-dbg` APT package. However, I couldn't find any information about debug symbols for the sapmachine jvm.

Clearly, these do not come with the sapmachine package itself since `gdb` command outputs:

```
user@host:~$ gdb /usr/lib/jvm/sapmachine-11/bin/java
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/jvm/sapmachine-11/bin/java...
(No debugging symbols found in /usr/lib/jvm/sapmachine-11/bin/java)
```

Could you please add instructions for installing the debug symbols to the README.md?

Thanks in advance.

**Comment by nice2mitja** [comment]
Hi @holy-moly-555, 

you will find the debug symbols as a separate download archive in the release section of each version. E.g. debug symbols for Linux-x64 and the latest version of SapMachine 18 are available here:
https://github.com/SAP/SapMachine/releases/download/sapmachine-18.0.1.1/sapmachine-jdk-18.0.1.1_linux-x64_bin-symbols.tar.gz

Make sure to download the symbols matching your local version of SapMachine. Extract the archive and copy the resulting `bin` and `lib` folder to the root directory of your SapMachine installation and you should be good to go. Please let me know if you have any issues. I will add some information to the README.md or Wiki. Let me check where it's located best and I'll make a proposal.

**Comment by nice2mitja** [comment]
No worries, it's great you got in touch and you are quite right about the missing documentation :) 

Do you think that would do? Or should we find a more prominent mention?
https://github.com/SAP/SapMachine/wiki/Frequently-Asked-Questions#where-can-i-find-sapmachine-debug-symbols

**Comment by holy-moly-555** [comment]
@nice2mitja no, it fits perfect on the FAQ page :-)

**Comment by nice2mitja** [comment]
Brilliant :)

I'm closing this issue, feel free to re-open, if there's anything else to do here!

**Comment by ginkel** [comment]
Hi there,

as I also just stumbled over this issue: I am using the SapMachine Docker base image in a [jib](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md)-based Docker build where it is difficult to just download and unpack symbols as one would do in a 'regular' Dockerfile-based build. Do you think it would make sense to offer a Docker image tag that includes debug symbols for such use-cases, e.g., `sapmachine:17-debug`?

Thanks,
Thilo

**Comment by nice2mitja** [comment]
Hi @ginkel, 

I understand. Would it be an option to add the debug symbols by means of the jib build? I'm not an expert on the topic, but it seems there are ways to add arbitrary files to your image:
https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md#adding-arbitrary-files-to-the-image

Cheers,
Mitja
