### ISSUE TITLE
[BUG] Windows Installer download URL on https://sap.github.io/SapMachine/ is wrong

### ISSUE THREAD

**Issue by 749** [SAP/SapMachine#1201]
## Behaviour:
- Select SAPMachine 11, SDK, Windows Installer, sapmachine-11.0.15.0.1
- The download URL currently points to a txt file with the sha256 for the download.
- `https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.15.0.1/sapmachine-jdk-11.0.15.0.1_windows-x64_bin.msi.sha256.txt`

## Expected:
- The download URL points to the msi file to install on windows
- `https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.15.0.1/sapmachine-jdk-11.0.15.0.1_windows-x64_bin.msi`

**Comment by RealCLanger** [comment]
Fixed now with https://github.com/SAP/SapMachine/commit/d04f65e1a7ed42cb98d36320d94c9e22868f867b. Sorry for the inconvenience.
