### ISSUE TITLE
JRE only and distroless image

### ISSUE THREAD

**Issue by wayzha** [SAP/SapMachine#1226]
Would like to check if we can provide JRE only (without full JDK) and distroless images? Thx

**Comment by nice2mitja** [comment]
Hi @wayzha,

thanks for getting in touch! Maybe you noticed that we provide JRE packages in the release section, e.g.:
https://github.com/SAP/SapMachine/releases/tag/sapmachine-11.0.16

However, I reckon you are looking for JRE docker images, correct?

With regards distroless, we are evaluating providing further container images, but haven't decided on it yet. Could you provide some information why distroless in particular would be interesting for you?

Thanks!

**Comment by wayzha** [comment]
> Hi @wayzha,
> 
> thanks for getting in touch! Maybe you noticed that we provide JRE packages in the release section, e.g.: https://github.com/SAP/SapMachine/releases/tag/sapmachine-11.0.16
> 
> However, I reckon you are looking for JRE docker images, correct?
> 
> With regards distroless, we are evaluating providing further container images, but haven't decided on it yet. Could you provide some information why distroless in particular would be interesting for you?
> 
> Thanks!

Thx for following that up. yes, we need JRE only docker images.
hope it can be distroless and non-root.
first of all, following least privilege principal, we should not offer a binary if that's not needed. and on the other side, SAP standards suggest a distroless/non-root image with bare mininal components in it:)

**Comment by nice2mitja** [comment]
Hi there,

for the time being, we have decided against offering a distroless-based SapMachine image, as our current focus is rather with [Cloud Native Buildpacks](https://buildpacks.io/). From our point of view this approach addresses also [other precious issues](https://buildpacks.io/features/), while dealing with image size and non-root users in unprivileged environments. There is a cloud native buildpack for [SapMachine](https://github.com/paketo-buildpacks/sap-machine).

Is it correct that both your requests derive from an SAP-context? If so, you should be able to benefit from CNB's as part of the Business Technology Platform (BTP) quite comfortably. 

I hope you understand :)
