### ISSUE TITLE
Merge SapMachine 11.0.16.1 and 17.0.4.1

### ISSUE THREAD

**Issue by RealCLanger** [SAP/SapMachine#1229]
We need to build SapMachine releases 11.0.16.1 and 17.0.4.1

**Comment by amosshi** [comment]
Hello @RealCLanger ,

- The `11.0.16.1` does not contain any artifact for `MacOS` - a bug ? - https://github.com/SAP/SapMachine/releases/tag/sapmachine-11.0.16.1
- While the 11.0.16 has them - https://github.com/SAP/SapMachine/releases/tag/sapmachine-11.0.16

**Comment by RealCLanger** [comment]
> Hello @RealCLanger ,
> 
> * The `11.0.16.1` does not contain any artifact for `MacOS` - a bug ? - https://github.com/SAP/SapMachine/releases/tag/sapmachine-11.0.16.1
> * While the 11.0.16 has them - https://github.com/SAP/SapMachine/releases/tag/sapmachine-11.0.16

Yes, you need to be patient for a little time. The MacOS binaries are build in a different process due to signing/notarization requirement. We're working on it and they should hopefully appear within the next 24 hours.

**Comment by RealCLanger** [comment]
Issue resolved via referenced PRs.
