### ISSUE TITLE
SapMachine JDK Installation for Alpine Linux 

### ISSUE THREAD

**Issue by turash104** [SAP/SapMachine#1234]
I am trying to install SapMachine 11 JDK in a docker container that uses Alpine Linux environment (alpine:3.16.2 docker). 

I have tried to install it by: 
apk add sapmachine-11-jdk;

The command fails with error: 
ERROR: unable to select packages:
          sapmachine-11-jdk (no such package) :
required by: world[sapmachine-11-jdk]

I was just wondering if there is a way to install SapMachine 11 JDK in Alpine Linux?

**Comment by MBaesken** [comment]
So far we only offert beta shipments for linuxx86_64  musl/Alpine,  **but only for SapMachine 17 and higher**.
See  https://github.com/SAP/SapMachine/releases/tag/sapmachine-17.0.4.1   (e.g.  [sapmachine-jdk-17.0.4.1-beta_linux-x64-musl_bin.tar.gz](https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.4.1/sapmachine-jdk-17.0.4.1-beta_linux-x64-musl_bin.tar.gz) .
