### ISSUE TITLE
sapmachine-jdk-17.0.5_macos-aarch64_bin.dmg is actually sapmachine-jdk-11.0.17+8_macos-x64_bin

### ISSUE THREAD

**Issue by rtrouton** [SAP/SapMachine#1265]
It appears that the wrong version of SapMachine is posted for the following download:

https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.5/sapmachine-jdk-17.0.5_macos-aarch64_bin.dmg

When downloaded and mounted, it appears to be SapMachine JDK 11.x for Intel instead of SapMachine JDK 17.x for Apple Silicon. Can this download please be updated with the correct SapMachine JDK 17 version?

**Comment by chalstrick** [comment]
I am checking ...

**Comment by chalstrick** [comment]
I restarted the upload for the macos binaries of 17.0.5 and 11.0.17. I expect the uploads to be done in the next hour. But I have to leave now and can only check the results this evening. But if you see the .dmg file to be uploaded again you may test it. I will test this evening

**Comment by chalstrick** [comment]
Now, after a restart of the upload the dmg files look good again. Thanks for detecting this

**Comment by RealCLanger** [comment]
Closing this ticket then. Please let us know if there are still issues.

**Comment by rtrouton** [comment]
Thanks, looks good now!
