### ISSUE TITLE
SAP GUI For Java Bugs

### ISSUE THREAD

**Issue by leialbert** [SAP/SapMachine#1274]
❯ jps
81243 Jps
31183
jstack 31183 > jstack.txt

> 2022-11-11 00:58:58
> Full thread dump OpenJDK 64-Bit Server VM (11.0.16+8-LTS-sapmachine mixed mode):
> 
> Threads class SMR info:
> _java_thread_list=0x0000600003294f80, length=29, elements={
> 0x00007fcef487b000, 0x00007fcef5860800, 0x00007fcef586e800, 0x00007fcef5873800,
> 0x00007fcef586f800, 0x00007fcef6816000, 0x00007fcef487e000, 0x00007fcef4895000,
> 0x00007fcef6848000, 0x00007fcef613d000, 0x00007fcef59e2000, 0x00007fcef616d800,
> 0x00007fcef69fb800, 0x00007fcef4eae000, 0x00007fcef9164800, 0x00007fcef681b800,
> 0x00007fcef5f34800, 0x00007fcef6ef5800, 0x00007fcef69c4800, 0x00007fcefb878800,
> 0x00007fcefa4fc800, 0x00007fcef6a08800, 0x00007fcefbb51000, 0x00007fcef6eb0000,
> 0x00007fcef654d000, 0x00007fcefa87d800, 0x00007fcefd0c4000, 0x00007fcef6537800,
> 0x00007fcefae3d000
> }
> 
> "Reference Handler" #2 daemon prio=10 os_prio=31 cpu=19.48ms elapsed=186376.80s allocated=0B defined_classes=0 tid=0x00007fcef487b000 nid=0x5703 waiting on condition  [0x000070000599a000]
>    java.lang.Thread.State: RUNNABLE
> 	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.16/Native Method)
> 	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.16/Reference.java:241)
> 	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.16/Reference.java:213)
> 
> "Finalizer" #3 daemon prio=8 os_prio=31 cpu=24.68ms elapsed=186376.80s allocated=3856B defined_classes=1 tid=0x00007fcef5860800 nid=0x5903 in Object.wait()  [0x0000700005a9d000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.16/ReferenceQueue.java:155)
> 	- waiting to re-lock in wait() <0x00000007800ebc28> (a java.lang.ref.ReferenceQueue$Lock)
> 	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.16/ReferenceQueue.java:176)
> 	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.16/Finalizer.java:170)
> 
> "Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=1.04ms elapsed=186376.78s allocated=560B defined_classes=0 tid=0x00007fcef586e800 nid=0x7a03 runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "Service Thread" #5 daemon prio=9 os_prio=31 cpu=0.04ms elapsed=186376.78s allocated=0B defined_classes=0 tid=0x00007fcef5873800 nid=0x5c03 runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "C2 CompilerThread0" #6 daemon prio=9 os_prio=31 cpu=66066.93ms elapsed=186376.78s allocated=1216B defined_classes=0 tid=0x00007fcef586f800 nid=0x5e03 waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
>    No compile task
> 
> "C1 CompilerThread0" #8 daemon prio=9 os_prio=31 cpu=10174.25ms elapsed=186376.78s allocated=66624B defined_classes=0 tid=0x00007fcef6816000 nid=0x6003 waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
>    No compile task
> 
> "Sweeper thread" #9 daemon prio=9 os_prio=31 cpu=194.26ms elapsed=186376.78s allocated=0B defined_classes=0 tid=0x00007fcef487e000 nid=0x6303 runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "Common-Cleaner" #10 daemon prio=8 os_prio=31 cpu=223.78ms elapsed=186376.73s allocated=56B defined_classes=0 tid=0x00007fcef4895000 nid=0x6603 in Object.wait()  [0x00007000060af000]
>    java.lang.Thread.State: TIMED_WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.16/ReferenceQueue.java:155)
> 	- waiting to re-lock in wait() <0x00000007807471a8> (a java.lang.ref.ReferenceQueue$Lock)
> 	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.16/CleanerImpl.java:148)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.16/InnocuousThread.java:161)
> 
> "JavaFX Application Thread" #11 daemon prio=5 os_prio=31 cpu=107602.52ms elapsed=186376.17s allocated=183M defined_classes=1844 tid=0x00007fcef6848000 nid=0x103 runnable  [0x00007ff7bcfdb000]
>    java.lang.Thread.State: RUNNABLE
> 	at sun.lwawt.macosx.LWCToolkit.doAWTRunLoopImpl(java.desktop@11.0.16/Native Method)
> 	at sun.lwawt.macosx.LWCToolkit.doAWTRunLoop(java.desktop@11.0.16/LWCToolkit.java:929)
> 	at sun.lwawt.macosx.LWCToolkit.invokeAndWait(java.desktop@11.0.16/LWCToolkit.java:710)
> 	at sun.lwawt.macosx.CInputMethod.characterIndexForPoint(java.desktop@11.0.16/CInputMethod.java:761)
> 	- locked <0x000000078f2240d0> (a sun.lwawt.macosx.CInputMethod)
> 
> "AWT-Shutdown" #12 prio=5 os_prio=31 cpu=41.97ms elapsed=186376.10s allocated=0B defined_classes=0 tid=0x00007fcef613d000 nid=0x9103 in Object.wait()  [0x00007000063b8000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.Object.wait(java.base@11.0.16/Object.java:328)
> 	at sun.awt.AWTAutoShutdown.run(java.desktop@11.0.16/AWTAutoShutdown.java:291)
> 	- waiting to re-lock in wait() <0x00000007807623e8> (a java.lang.Object)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "AWT-EventQueue-0" #13 prio=6 os_prio=31 cpu=36846.45ms elapsed=186375.91s allocated=3198M defined_classes=3755 tid=0x00007fcef59e2000 nid=0xcd13 waiting on condition  [0x0000700006641000]
>    java.lang.Thread.State: WAITING (parking)
> 	at jdk.internal.misc.Unsafe.park(java.base@11.0.16/Native Method)
> 	- parking to wait for  <0x000000078e901490> (a java.util.concurrent.FutureTask)
> 	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.16/LockSupport.java:194)
> 	at java.util.concurrent.FutureTask.awaitDone(java.base@11.0.16/FutureTask.java:447)
> 	at java.util.concurrent.FutureTask.get(java.base@11.0.16/FutureTask.java:190)
> 	at com.sun.javafx.webkit.InputMethodClientImpl.getLocationOffset(javafx.web/InputMethodClientImpl.java:155)
> 	at javafx.scene.Scene$InputMethodRequestsDelegate.getLocationOffset(javafx.graphics/Scene.java:4118)
> 	at javafx.embed.swing.InputMethodSupport$InputMethodRequestsAdapter.getLocationOffset(javafx.swing/InputMethodSupport.java:67)
> 	at sun.awt.im.InputMethodContext.getLocationOffset(java.desktop@11.0.16/InputMethodContext.java:285)
> 	at sun.lwawt.macosx.CInputMethod$7.run(java.desktop@11.0.16/CInputMethod.java:763)
> 	- locked <0x000000078e949da0> (a [Ljava.awt.font.TextHitInfo;)
> 	at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.16/InvocationEvent.java:303)
> 	at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.16/EventQueue.java:770)
> 	at java.awt.EventQueue$4.run(java.desktop@11.0.16/EventQueue.java:721)
> 	at java.awt.EventQueue$4.run(java.desktop@11.0.16/EventQueue.java:715)
> 	at java.security.AccessController.doPrivileged(java.base@11.0.16/Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.16/ProtectionDomain.java:85)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.16/ProtectionDomain.java:95)
> 	at java.awt.EventQueue$5.run(java.desktop@11.0.16/EventQueue.java:745)
> 	at java.awt.EventQueue$5.run(java.desktop@11.0.16/EventQueue.java:743)
> 	at java.security.AccessController.doPrivileged(java.base@11.0.16/Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.16/ProtectionDomain.java:85)
> 	at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.16/EventQueue.java:742)
> 	at com.sap.platin.micro.event.GuiEventQueue.dispatchEvent(GuiEventQueue.java:110)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.16/EventDispatchThread.java:203)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.16/EventDispatchThread.java:124)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.16/EventDispatchThread.java:113)
> 	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.16/EventDispatchThread.java:109)
> 	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.16/EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.run(java.desktop@11.0.16/EventDispatchThread.java:90)
> 
> "Java2D Queue Flusher" #14 daemon prio=10 os_prio=31 cpu=11562.13ms elapsed=186375.81s allocated=1952B defined_classes=0 tid=0x00007fcef616d800 nid=0x10703 in Object.wait()  [0x0000700006747000]
>    java.lang.Thread.State: TIMED_WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(java.desktop@11.0.16/OGLRenderQueue.java:205)
> 	- waiting to re-lock in wait() <0x0000000780762880> (a sun.java2d.opengl.OGLRenderQueue$QueueFlusher)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "Java2D Disposer" #15 daemon prio=10 os_prio=31 cpu=30.66ms elapsed=186375.56s allocated=1184B defined_classes=1 tid=0x00007fcef69fb800 nid=0x1460b in Object.wait()  [0x000070000684a000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.16/ReferenceQueue.java:155)
> 	- waiting to re-lock in wait() <0x0000000780762e18> (a java.lang.ref.ReferenceQueue$Lock)
> 	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.16/ReferenceQueue.java:176)
> 	at sun.java2d.Disposer.run(java.desktop@11.0.16/Disposer.java:144)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "DestroyJavaVM" #25 prio=5 os_prio=31 cpu=1813.68ms elapsed=186370.00s allocated=480B defined_classes=0 tid=0x00007fcef4eae000 nid=0x3d03 waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "TimerQueue" #26 daemon prio=5 os_prio=31 cpu=411.42ms elapsed=186369.73s allocated=701K defined_classes=2 tid=0x00007fcef9164800 nid=0xb37b waiting on condition  [0x0000700006d80000]
>    java.lang.Thread.State: WAITING (parking)
> 	at jdk.internal.misc.Unsafe.park(java.base@11.0.16/Native Method)
> 	- parking to wait for  <0x00000007821ea5d0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
> 	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.16/LockSupport.java:194)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.16/AbstractQueuedSynchronizer.java:2081)
> 	at java.util.concurrent.DelayQueue.take(java.base@11.0.16/DelayQueue.java:217)
> 	at javax.swing.TimerQueue.run(java.desktop@11.0.16/TimerQueue.java:171)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "NovaFocusPainter.AnimationThread" #27 daemon prio=6 os_prio=31 cpu=6.47ms elapsed=186369.29s allocated=143K defined_classes=8 tid=0x00007fcef681b800 nid=0x15a4b in Object.wait()  [0x0000700006e83000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.Object.wait(java.base@11.0.16/Object.java:328)
> 	at com.sap.plaf.synth.NovaFocusPaintManager$AnimationThread.run(NovaFocusPaintManager.java:1494)
> 	- waiting to re-lock in wait() <0x0000000782c001a8> (a java.util.Vector)
> 
> "PersistenceManager.WriterThread" #33 daemon prio=6 os_prio=31 cpu=0.68ms elapsed=186366.32s allocated=51216B defined_classes=1 tid=0x00007fcef5f34800 nid=0x1ec03 in Object.wait()  [0x0000700007570000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.Object.wait(java.base@11.0.16/Object.java:328)
> 	at com.sap.platin.base.util.PersistenceManager$WriterThread.waitForWork(PersistenceManager.java:1678)
> 	- waiting to re-lock in wait() <0x0000000783154908> (a com.sap.platin.base.util.PersistenceManager$WriterThread)
> 	at com.sap.platin.base.util.PersistenceManager$WriterThread$1.run(PersistenceManager.java:1639)
> 	at java.security.AccessController.doPrivileged(java.base@11.0.16/Native Method)
> 	at javax.security.auth.Subject.doAsPrivileged(java.base@11.0.16/Subject.java:484)
> 	at com.sap.platin.base.util.PersistenceManager$WriterThread.run(PersistenceManager.java:1627)
> 
> "QuantumRenderer-0" #74 daemon prio=6 os_prio=31 cpu=311.57ms elapsed=186288.74s allocated=4006K defined_classes=164 tid=0x00007fcef6ef5800 nid=0x13363 waiting on condition  [0x000070000787a000]
>    java.lang.Thread.State: WAITING (parking)
> 	at jdk.internal.misc.Unsafe.park(java.base@11.0.16/Native Method)
> 	- parking to wait for  <0x0000000786146e38> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
> 	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.16/LockSupport.java:194)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.16/AbstractQueuedSynchronizer.java:2081)
> 	at java.util.concurrent.LinkedBlockingQueue.take(java.base@11.0.16/LinkedBlockingQueue.java:433)
> 	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.16/ThreadPoolExecutor.java:1054)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.16/ThreadPoolExecutor.java:1114)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.16/ThreadPoolExecutor.java:628)
> 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(javafx.graphics/QuantumRenderer.java:125)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "Prism Font Disposer" #76 daemon prio=10 os_prio=31 cpu=1.22ms elapsed=186288.68s allocated=0B defined_classes=0 tid=0x00007fcef69c4800 nid=0x1697b in Object.wait()  [0x000070000797d000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.16/ReferenceQueue.java:155)
> 	- waiting to re-lock in wait() <0x0000000786147198> (a java.lang.ref.ReferenceQueue$Lock)
> 	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.16/ReferenceQueue.java:176)
> 	at com.sun.javafx.font.Disposer.run(javafx.graphics/Disposer.java:93)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "InvokeLaterDispatcher" #79 daemon prio=6 os_prio=31 cpu=24154.11ms elapsed=186288.61s allocated=10955K defined_classes=1 tid=0x00007fcefb878800 nid=0x17c03 in Object.wait()  [0x0000700007b83000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.Object.wait(java.base@11.0.16/Object.java:328)
> 	at com.sun.glass.ui.InvokeLaterDispatcher.run(javafx.graphics/InvokeLaterDispatcher.java:127)
> 	- waiting to re-lock in wait() <0x0000000786150540> (a java.lang.StringBuilder)
> 
> "Thread-46" #80 daemon prio=5 os_prio=31 cpu=11075.53ms elapsed=186288.55s allocated=3307K defined_classes=0 tid=0x00007fcefa4fc800 nid=0x1dc03 runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "Disposer" #81 daemon prio=10 os_prio=31 cpu=21.97ms elapsed=186287.46s allocated=116K defined_classes=1 tid=0x00007fcef6a08800 nid=0x1da03 in Object.wait()  [0x0000700007a80000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.16/ReferenceQueue.java:155)
> 	- waiting to re-lock in wait() <0x00000007861508a8> (a java.lang.ref.ReferenceQueue$Lock)
> 	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.16/ReferenceQueue.java:176)
> 	at com.sun.webkit.Disposer.run(javafx.web/Disposer.java:122)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "ReaderThread5" #237 daemon prio=6 os_prio=31 cpu=16.96ms elapsed=267.13s allocated=7584B defined_classes=0 tid=0x00007fcefbb51000 nid=0x127f3 runnable  [0x00007000072eb000]
>    java.lang.Thread.State: RUNNABLE
> 	at com.sap.platin.r3.protocol.ni.JniAgComAdaptor.jniRead(Native Method)
> 	at com.sap.platin.r3.protocol.ni.JniAgComAdaptor.read(JniAgComAdaptor.java:58)
> 	at com.sap.platin.r3.protocol.ni.GuiNiReaderThread.run(GuiNiReaderThread.java:91)
> 
> "GuiWriterThread14" #238 daemon prio=6 os_prio=31 cpu=11.03ms elapsed=267.13s allocated=11080B defined_classes=0 tid=0x00007fcef6eb0000 nid=0x19c3b in Object.wait()  [0x00007000073ee000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.Object.wait(java.base@11.0.16/Object.java:328)
> 	at com.sap.platin.base.protocol.GuiMultiplexer.waitForWork(GuiMultiplexer.java:168)
> 	- waiting to re-lock in wait() <0x0000000782078220> (a com.sap.platin.base.protocol.GuiMultiplexer)
> 	at com.sap.platin.base.protocol.GuiMultiplexer.run(GuiMultiplexer.java:46)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "GuiMultiplexer(Connection)15" #239 daemon prio=6 os_prio=31 cpu=191.57ms elapsed=267.13s allocated=4259K defined_classes=0 tid=0x00007fcef654d000 nid=0x16d6b in Object.wait()  [0x0000700007674000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.Object.wait(java.base@11.0.16/Object.java:328)
> 	at com.sap.platin.base.protocol.GuiMultiplexer.waitForWork(GuiMultiplexer.java:168)
> 	- waiting to re-lock in wait() <0x00000007820783b8> (a com.sap.platin.base.protocol.GuiMultiplexer)
> 	at com.sap.platin.base.protocol.GuiMultiplexer.run(GuiMultiplexer.java:46)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "GuiMultiplexer(Session)16" #240 daemon prio=6 os_prio=31 cpu=622.99ms elapsed=266.92s allocated=21609K defined_classes=445 tid=0x00007fcefa87d800 nid=0x12f63 in Object.wait()  [0x0000700007165000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.Object.wait(java.base@11.0.16/Object.java:328)
> 	at com.sap.platin.base.protocol.GuiMultiplexer.waitForWork(GuiMultiplexer.java:168)
> 	- waiting to re-lock in wait() <0x0000000782078550> (a com.sap.platin.base.protocol.GuiMultiplexer)
> 	at com.sap.platin.base.protocol.GuiMultiplexer.run(GuiMultiplexer.java:46)
> 	at java.lang.Thread.run(java.base@11.0.16/Thread.java:829)
> 
> "CustomGlassPane Timer" #260 daemon prio=6 os_prio=31 cpu=0.81ms elapsed=222.21s allocated=2024B defined_classes=0 tid=0x00007fcefd0c4000 nid=0x1915b in Object.wait()  [0x0000700007c86000]
>    java.lang.Thread.State: WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.lang.Object.wait(java.base@11.0.16/Object.java:328)
> 	at java.util.TimerThread.mainLoop(java.base@11.0.16/Timer.java:527)
> 	- waiting to re-lock in wait() <0x000000078ef0b128> (a java.util.TaskQueue)
> 	at java.util.TimerThread.run(java.base@11.0.16/Timer.java:506)
> 
> "Timer-27" #263 daemon prio=6 os_prio=31 cpu=65.25ms elapsed=217.20s allocated=0B defined_classes=0 tid=0x00007fcef6537800 nid=0x19aef in Object.wait()  [0x0000700007e8c000]
>    java.lang.Thread.State: TIMED_WAITING (on object monitor)
> 	at java.lang.Object.wait(java.base@11.0.16/Native Method)
> 	- waiting on <no object reference available>
> 	at java.util.TimerThread.mainLoop(java.base@11.0.16/Timer.java:553)
> 	- waiting to re-lock in wait() <0x000000078e94c720> (a java.util.TaskQueue)
> 	at java.util.TimerThread.run(java.base@11.0.16/Timer.java:506)
> 
> "Attach Listener" #264 daemon prio=9 os_prio=31 cpu=6.26ms elapsed=0.12s allocated=0B defined_classes=0 tid=0x00007fcefae3d000 nid=0x1968f waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "VM Thread" os_prio=31 cpu=1521.41ms elapsed=186376.81s tid=0x00007fcef6811000 nid=0x4a03 runnable  
> 
> "GC Thread#0" os_prio=31 cpu=2144.51ms elapsed=186376.83s tid=0x00007fcef5816000 nid=0x5303 runnable  
> 
> "GC Thread#1" os_prio=31 cpu=2155.93ms elapsed=186375.54s tid=0x00007fcef4890000 nid=0x12407 runnable  
> 
> "GC Thread#2" os_prio=31 cpu=2149.78ms elapsed=186375.54s tid=0x00007fcef61af000 nid=0x1120f runnable  
> 
> "GC Thread#3" os_prio=31 cpu=2088.66ms elapsed=186375.54s tid=0x00007fcef4a60000 nid=0x13703 runnable  
> 
> "G1 Main Marker" os_prio=31 cpu=29.49ms elapsed=186376.83s tid=0x00007fcef5852000 nid=0x5103 runnable  
> 
> "G1 Conc#0" os_prio=31 cpu=15479.38ms elapsed=186376.83s tid=0x00007fcef5852800 nid=0x5003 runnable  
> 
> "G1 Refine#0" os_prio=31 cpu=36.42ms elapsed=186376.83s tid=0x00007fcef4869000 nid=0x4e03 runnable  
> 
> "G1 Refine#1" os_prio=31 cpu=5.11ms elapsed=186374.12s tid=0x00007fcef646e000 nid=0x15513 runnable  
> 
> "G1 Young RemSet Sampling" os_prio=31 cpu=2182.89ms elapsed=186376.83s tid=0x00007fcef486a000 nid=0x4703 runnable  
> "VM Periodic Task Thread" os_prio=31 cpu=2669.25ms elapsed=186376.70s tid=0x00007fcef6016000 nid=0x6a03 waiting on condition  
> 
> "vitals sampler thread" os_prio=31 cpu=495.65ms elapsed=186376.70s tid=0x00007fcef6811800 nid=0x6803 waiting on condition  
> 
> JNI global refs: 744, weak refs: 198

**Comment by MBaesken** [comment]
Could you be a bit more specific what process 31183 is, and why you opened the issue at Sapmachine ?

**Comment by RealCLanger** [comment]
Closing due to missing information.
