### ISSUE TITLE
HttpURLConnection: Should allow PATCH HTTP Method

### ISSUE THREAD

**Issue by 749** [SAP/SapMachine#1278]
The Library paypalhttp in version 2.0.0 or version 1.0.1 uses HttpURLConnection to send a PATCH request to the paypal API.

The library includes a "hack" to add the PATCH method to the following static variable:

See: https://github.com/SAP/SapMachine/blame/b8aa5adf1b7664d0ab534ff640bd74230151c13b/src/java.base/share/classes/java/net/HttpURLConnection.java#L361

Unfortunately this "hack" does not work anymore, even when adding the jvm parameter: `--add-opens=java.base/java.net=ALL-UNNAMED`

I think this should be considered a bug in the JVM and the `PATCH` HTTP method should be added to the static variable `java.net.HttpURLConnection::methods`.

**Comment by RealCLanger** [comment]
Hi, @749.

Please see this OpenJDK JBS item about this problem: https://bugs.openjdk.org/browse/JDK-8207840

It was closed as won't fix. The suggestion is to resort to the new HTTP client implementation from module java.net.http. Do you know if that's possible or the paypalhttp library has already implemented this in some version?

**Comment by 749** [comment]
Hi @RealCLanger,

unfortunately `2.0.0` is the latest version. Do you know of any other way we could "fix" the hack?

**Comment by RealCLanger** [comment]
Did it work with SapMachine 11? Do you have some more details on why --add-opens doesn't work?

**Comment by 749** [comment]
Yes it did work with SapMachine 11. We identified that we --add-open the wrong package, I will update as soon as we have further debugged the issue.

**Comment by 749** [comment]
`--add-opens=java.base/sun.net.www.protocol.https=ALL-UNNAMED` was the required --add-opens for the paypalhttp lib.
@RealCLanger thanks for the help!

**Comment by RealCLanger** [comment]
Cool. Glad that you could solve it. 🙂
