### ISSUE TITLE
Support for update-java-alternatives in Docker image

### ISSUE THREAD

**Issue by pascalwill** [SAP/SapMachine#1282]
Please provide support for the command [`update-java-alternatives`](https://manpages.ubuntu.com/manpages/focal/man8/update-java-alternatives.8.html) in SapMachine Docker images.

This would allow for switching between different installed JDKs easily with a single command. This helps especially in cases where the default OpenJDK gets installed though a package dependency and overrides SapMachine.

For this a `.jinfo` file must be provided, similarly as found for example in [openjdk-11-jre-headless](https://packages.ubuntu.com/focal/openjdk-11-jre-headless).

**Comment by MBaesken** [comment]
Not sure if the .jinfo file is really documented.
Looks like something similar to https://codetrips.com/2020/12/29/support-multiple-jdks-in-ubuntu/  is wanted here.

**Comment by RealCLanger** [comment]
We've implemented some support with this change in our infrastructure repo: https://github.com/SAP/SapMachine-infrastructure/commit/67a99e3758f521d904400696a19d5c07d9708ad9

The upcoming packages for the next week's due July update should support update-java-alternatives. Please test it out then and report any issues.
