### ISSUE TITLE
[Question] Vulnerabilities are reported in JRE (v11.0.17u8 ) 

### ISSUE THREAD

**Issue by NutDhu** [SAP/SapMachine#1347]
My Security Scan tool report that jdk-sapmachine-11.0.17u8 has vulnerabilities,  that can not find some dependency package versions:
freetype: unknow
lcms:unknow
giflib:unnow
Would you please help me check the versions about above dependency packages?
check below screen shot:
![image](https://user-images.githubusercontent.com/33240440/219542223-8428f1b8-f965-44f8-bbec-368860f0ef75.png)
![image](https://user-images.githubusercontent.com/33240440/219542296-d43e3a2f-446e-43d7-8b5f-cecd737fec1b.png)
![image](https://user-images.githubusercontent.com/33240440/219542377-5b7ac59d-5214-4865-8bdf-af8ba9efc8b0.png)
![image](https://user-images.githubusercontent.com/33240440/219542430-5b6fda37-9a59-4812-ad16-c30de93e85d2.png)

**Comment by ArnoZeller** [comment]
Hi NutDhu,

for the version numbers of included open source libs in SapMachine you can have a look at the legal folders of SapMachine.
The folder legal of a SapMachine download contains several subfolders that contain the information for each module - i.e.
for freetype you can look at **legal/java.desktop/freetype.md** and will see SapMachine 11.0.17+8 contains freetye **v2.12.1**.
You can also look directly in GitHub for the source of 11.0.17+8 (https://github.com/SAP/SapMachine/tree/jdk-11.0.17%2B8).
There the information can be found at https://github.com/SAP/SapMachine/blob/jdk-11.0.17%2B8/src/java.desktop/share/legal/freetype.md

Same is for giflib - either **legal/java.desktop/giflib.md** in the download or https://github.com/SAP/SapMachine/blob/jdk-11.0.17%2B8/src/java.desktop/share/legal/giflib.md at GitHub.

The giflib used in SapMachine 11.0.17+8 is **v5.2.1**

Should you be a SAP employee, you can contact me directly for further questions

Best regards,
Arno Zeller
