### ISSUE TITLE
Unhandled exception in Buildpack main method

### ISSUE THREAD

**Issue by adamandre79** [SAP/SapMachine#1368]
Hello,

we have in several projects this error:
Unhandled exception in Buildpack main method:
https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.18/sapmachine-jdk-11.0.18_linux-x64_bin.tar.gz
returned '429', download failed. (STDERR, STG)#

Same also for Java 17. 

Could you please check?

Regards
André

**Comment by DanieleStrafile** [comment]
We are experiencing the same problem. It is blocking our delivery pipeline!!

**Comment by RealCLanger** [comment]
Hi,

the error says: 429 - Rate limit exceeded. There's nothing we can do about this from SapMachine. Maybe GitHub itself changed/lowered some rates for cloning repositories. A way to workaround this would be if you could somehow authenticate to github when downloading. But not sure how feasible that is.

After all, you have to check this together with your Cloud Foundry installation provider.

Best regards
Christoph

**Comment by DanieleStrafile** [comment]
> Hi,
> 
> the error says: 429 - Rate limit exceeded. There's nothing we can do about this from SapMachine. Maybe GitHub itself changed/lowered some rates for cloning repositories. A way to workaround this would be if you could somehow authenticate to github when downloading. But not sure how feasible that is.
> 
> After all, you have to check this together with your Cloud Foundry installation provider.
> 
> Best regards Christoph

Hello @RealCLanger what do you mean with Cloud Foundry "installation provider"?

**Comment by RealCLanger** [comment]
> > Hi,
> > the error says: 429 - Rate limit exceeded. There's nothing we can do about this from SapMachine. Maybe GitHub itself changed/lowered some rates for cloning repositories. A way to workaround this would be if you could somehow authenticate to github when downloading. But not sure how feasible that is.
> > After all, you have to check this together with your Cloud Foundry installation provider.
> > Best regards Christoph
> 
> Hello @RealCLanger what do you mean with Cloud Foundry "installation provider"?

I guess you're using the buildpack on a Cloud Foundry instance. If it is SAP BTP, then the SAP BTP team is aware of it and probably working on a resolution.
