### ISSUE TITLE
Huge memory consumption after upgrading SAP Machine 17

### ISSUE THREAD

**Issue by kanchan123rai** [SAP/SapMachine#1395]
Dear colleagues,

We are facing huge memory consumption issue in Asset Performance Management service(rc-service) after upgrading SAP Machine 17

Below is the config in our application mta.yaml file for java:

JAVA_OPTS: "-XX:MaxDirectMemorySize=200M -XX:NewSize=3G -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution"
      JBP_CONFIG_JAVA_OPTS: "[java_opts: '-XX:MaxDirectMemorySize=200M -XX:NewSize=3G -XX:+PrintGCDetails']"
      JBP_CONFIG_COMPONENTS: "jres: ['com.sap.xs.java.buildpack.jre.SAPMachineJRE']"
      JBP_CONFIG_SAP_MACHINE_JRE: "{ use_offline_repository: false, version: 17.+ }"

repository: https://github.tools.sap/AssetPerformanceManagement/rc-assessment .

Attaching screenshot of memory utilization in our application before and after updating JDK:

With java 8
![image](https://user-images.githubusercontent.com/131359812/233363279-3064bb06-2d85-46c6-bfcf-422adf0a397b.png)

With java 17
![image](https://user-images.githubusercontent.com/131359812/233362274-f6225b56-e730-4d7e-a57d-2122fcfdf133.png)

Is there any solution for this?

Thank you!
Kanchan Rai

**Comment by ansteiner** [comment]
@kanchan123rai: As this is an issue in BTP CF, please open a [Jtrack ](https://jtrack.wdf.sap.corp/secure/CreateIssue!default.jspa) issue on "Java JDK" to follow up with this.

**Comment by kanchan123rai** [comment]
@ansteiner Thanks! Sure will open jtrack issue.
