### ISSUE TITLE
SAPgui for Java: random crashes (Linux/wayland)

### ISSUE THREAD

**Issue by bobblkabb** [SAP/SapMachine#1397]
Hello,

running latest SAPgui 7.8 Patchlevel 2 on openSUSE Tumbleweed (wayland). Sometimes I can work a little while, sometimes it crashes pretty soon. It just disappears.
Tried different openjdk versions. First I had openjdk 11, than the latest 19  and now I got openjdk 17 installed. Doesn't make a difference.

[hs_err_pid5785.log](https://github.com/SAP/SapMachine/files/11307828/hs_err_pid5785.log)

After crash I can't start SAPgui anymore, need to reboot the computer.

BR,
Michael

**Comment by RealCLanger** [comment]
Hi @bobblkabb,

this seems to be an issue with SAP GUI for Java (cc @woersi) which uses Java FX. Can you please open a ticket with SAP Support on component BC-FES-JAV? If the colleagues figure out that it has to do with SapMachine, they will contact us.

With that I'm closing this issue. Thanks for your understanding.

BR,
Christoph
