### ISSUE TITLE
Remote desktop problem with SAP B1 HANA 

### ISSUE THREAD

**Issue by leansokcheang** [SAP/SapMachine#1426]
When i using remote desktop from windows client to suse linux enterprise server 15 sp3 for sap application, it can not run Hana Studio.but when i access by web browser directly to my suse linux enterprise server, it can run Hana studio .

**Comment by RealCLanger** [comment]
Hi,
this should be reported to the Hana Studio support channels then (e.g. SAP ticketing system).
Thanks
Christoph

**Comment by leansokcheang** [comment]
so what is the solution to fix it ?

**Comment by RealCLanger** [comment]
> so what is the solution to fix it ?

As I said, please contact the right channel of support, maybe they can help. We (from SapMachine team) can't, as per the synopsis.
