### ISSUE TITLE
SapMachine 17 Installers

### ISSUE THREAD

**Issue by stba42** [SAP/SapMachine#1499]
Hello,

the installers for SapMachine 17 seem to be missing, they are there for 20 and 11 but not 17

**Comment by steveschnepp** [comment]
I was also searching for the 17 MSI files, and it seems **only releases have them**. Pre-release don't.

See in [17.0.8](https://github.com/SAP/SapMachine/releases/tag/sapmachine-17.0.8) for the [JDK](https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.8/sapmachine-jdk-17.0.8_windows-x64_bin.msi) and the [JRE](https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.8/sapmachine-jre-17.0.8_windows-x64_bin.msi).

**Comment by RealCLanger** [comment]
Hi @stba42,

you're right with your observation. We've just started to release a respin of 17.0.8 (17.0.8.1) and 11.0.20 (11.0.20.1). The Windows installer binaries are not available yet but will be delivered sone. For the time being, please resort to the installer available for the 17.0.8 release (https://github.com/SAP/SapMachine/releases/tag/sapmachine-17.0.8).

Cheers
Christoph

**Comment by RealCLanger** [comment]
This should be solved now.
