### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) 

### ISSUE THREAD

**Issue by majoly83** [SAP/SapMachine#1509]
Good day.

We are running SAP Commerce 2011 on multiple servers with SAPMachine 11.0.20.1 . We have been getting since the 15 of September the following errors on all our environments (See below).

The log does not give me much info to work with except that "Something" within Java failed. It mostly happens immediately after the SAPCommerce software has finished booting, it can sometimes take multiple attempts before it starts without crashing

We can't figure out what is going on and where to start looking. All we know is that we have not performed any code changes that could of triggered the issue.

Any suggestion?

Thank you

#
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | # A fatal error has been detected by the Java Runtime Environment:
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | #
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000aeaa7af207, pid=4868, tid=5448
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | #
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | # JRE version: OpenJDK Runtime Environment SapMachine (11.0.20.1+1) (build 11.0.20.1+1-LTS-sapmachine)
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | # Java VM: OpenJDK 64-Bit Server VM SapMachine (11.0.20.1+1-LTS-sapmachine, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | # Problematic frame:
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | # J 41520 c2 org.apache.catalina.core.ApplicationHttpRequest.removeSpecial(Ljava/lang/String;)Z (39 bytes) @ 0x000000aeaa7af207 [0x000000aeaa7af0a0+0x0000000000000167]
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | #
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | # Core dump will be written. Default location: D:\workspace.2011\hybris\bin\platform\tomcat\bin\hs_err_pid4868.mdmp
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | #
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | # An error report file with more information is saved as:
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | # D:\workspace.2011\hybris\bin\platform\tomcat\bin\hs_err_pid4868.log
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 | Compiled method (c2)  518896 41520       4       org.apache.catalina.core.ApplicationHttpRequest::removeSpecial (39 bytes)
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  total in heap  [0x000000aeaa7aef10,0x000000aeaa7af488] = 1400
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  relocation     [0x000000aeaa7af088,0x000000aeaa7af098] = 16
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  main code      [0x000000aeaa7af0a0,0x000000aeaa7af3c0] = 800
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  stub code      [0x000000aeaa7af3c0,0x000000aeaa7af3d8] = 24
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  oops           [0x000000aeaa7af3d8,0x000000aeaa7af3e0] = 8
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  metadata       [0x000000aeaa7af3e0,0x000000aeaa7af400] = 32
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  scopes data    [0x000000aeaa7af400,0x000000aeaa7af428] = 40
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  scopes pcs     [0x000000aeaa7af428,0x000000aeaa7af468] = 64
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  dependencies   [0x000000aeaa7af468,0x000000aeaa7af478] = 16
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:41.956 |  nul chk table  [0x000000aeaa7af478,0x000000aeaa7af488] = 16
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 | Compiled method (c1)  519141 31831       2       javax.servlet.http.HttpServletRequestWrapper::getSession (11 bytes)
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  total in heap  [0x000000aea6b55190,0x000000aea6b55570] = 992
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  relocation     [0x000000aea6b55308,0x000000aea6b55340] = 56
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  main code      [0x000000aea6b55340,0x000000aea6b55480] = 320
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  stub code      [0x000000aea6b55480,0x000000aea6b554c8] = 72
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  oops           [0x000000aea6b554c8,0x000000aea6b554d0] = 8
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  metadata       [0x000000aea6b554d0,0x000000aea6b554e8] = 24
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  scopes data    [0x000000aea6b554e8,0x000000aea6b55518] = 48
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  scopes pcs     [0x000000aea6b55518,0x000000aea6b55568] = 80
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  dependencies   [0x000000aea6b55568,0x000000aea6b55570] = 8
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 | Compiled method (c1)  519154 40507       2       org.apache.catalina.core.ApplicationHttpRequest::removeAttribute (19 bytes)
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  total in heap  [0x000000aea712df10,0x000000aea712e2f0] = 992
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  relocation     [0x000000aea712e088,0x000000aea712e0c8] = 64
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  main code      [0x000000aea712e0e0,0x000000aea712e200] = 288
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  stub code      [0x000000aea712e200,0x000000aea712e258] = 88
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  oops           [0x000000aea712e258,0x000000aea712e260] = 8
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  metadata       [0x000000aea712e260,0x000000aea712e278] = 24
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  scopes data    [0x000000aea712e278,0x000000aea712e298] = 32
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  scopes pcs     [0x000000aea712e298,0x000000aea712e2e8] = 80
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 |  dependencies   [0x000000aea712e2e8,0x000000aea712e2f0] = 8
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:42.259 | Could not load hsdis-amd64.dll; library not loadable; PrintAssembly is disabled
INFO   | jvm 1    | srvmain | 2023/09/25 20:29:43.467 | Could not obtain stack trace. StackWalk64 failed

**Comment by ansteiner** [comment]
Please provide the D:\workspace.2011\hybris\bin\platform\tomcat\bin\hs_err_pid4868.log for further investigation. Are you facing this issue after you updated to SapMachine 11.0.20.1? If yes, which version was working fine before?

**Comment by majoly83** [comment]
[hs_err_pid4868.log](https://github.com/SAP/SapMachine/files/12726106/hs_err_pid4868.log)
Here is the log file.

We actually upgraded to SAP Machine 11.0.20.1 this week-end in desperation hoping the newest revision of 11 would help but sadly it didn't change anything.

Before this week-end we were running SAP Machine 11.0.12 and it has been stable for almost 2 years now.

Thank you

**Comment by ansteiner** [comment]
Hi,
SAP Commerce 2011 is no longer in maintenance by SAP(End of maintenance was March 31, 2023). Also the OS Windows Server 2012 R2 you are using will go out of maintenance in October 10 2023). Are there any plans to upgrade these systems? 

Did I get it right that it was running till this week-end on SapMachine 11.0.12 without an issue and you updated this week-end directly to 11.0.20.1 or did you try other versions too? Would be helpful to know the last working version, as there is not that much information in the hs_err file.(I removed the link of the hs_err file).
Kind regards,
Andreas

**Comment by majoly83** [comment]
Hello Andreas.
Thanks for the quick reply

We are a bit behind for the upgrade of SAP Commerce but it is planned to be upgraded to 2205 within the coming weeks.
As for Windows all our instances are being replaced as we speak so within the next weeks, the new servers with Windows 2022 will be live.

To answer your questions regarding SAPMachine, we were running 11.0.12 for the last 2 years at least on all our environments and without any issues. The exception I reported started happening 2 weeks ago on all our environments. The log file and dump does not indeed much information so we thought it would worth the risk to upgrade to the latest revision of SAPMachine in hope there would of been a known issue resolved in the latest revision, but sadly the issue is somewhere else.

This switch from 11.0.12 to 11.0.20.1 happened this Saturday, and the exception didn't go away.

In terms of code change, almost nothing had been done, and as a test, we downgraded to a version before the crash started and the exception is still  happening.

So from there the possibilities are.

1 - Some issue within Windows (or another app) causing the crash, we will investigate and see if something was changed on our servers
2 - Content causing issues (We uploaded new locale info to all our components not long ago to support a new language for our website)
3 - FrontEnd bug ?

Hope this can help a bit, and if all of this seem to be a bit confusing I'm sorry, as we are a bit lost as well on what could be happening.

I'm sure the SAPMachine has nothing to do, but we thought it would worth it to at least try and report the issue in hope this could have been seen before.

Thank you very much
Marc-André

**Comment by majoly83** [comment]
As an update.
Our antivirus SentinelOne could potentially be responsable for the failures.

An update was applied a few days before the first crash.
As a test we added the directory of our SAPCommerce to the exclusion for scanning in hope it will help.

Time will tell..

**Comment by ansteiner** [comment]
Hi Marc-André,
as this happend with earlier SapMachine version too, it unlikely that this is caused by SapMachine. You mentioned the  SentinelOne update, which could cause such issues. I found some similar issue. If possible, disable/remove the SentinalOne agent to verify if this is the root cause. Let me know if the exclusion will resolve the issue already.
In case you want further support from us, you should open an incident with SAP and let me know the incident number to follow-up with this. Through the SAP incident other logs or dumps could be provided, if necessary. 
Kind regards,
Andreas

**Comment by MBaesken** [comment]
> Our antivirus SentinelOne could potentially be responsable for the failures.

Hi, is there some update regarding SentinelOne  disabling ? Has this helped?

**Comment by majoly83** [comment]
Good day.
We were unable to confirm yet that SentinelOne is responsible for all the failures we are having lately.

We did some testing last week with it disabled for a few hours and attempted to retrigger the problem and it never happened, we were sceptical if that really helped because we attempted to reproduce it after it was turned back on and we had no luck.

For now what we have done is put the sapmachine directory in the exclusion for SentinelOne (before we only added SAPCommerce directory) and we shall see if it makes things better.

As an extra bit of information, our instances of SentinelOne went from version 22.2.4.558 to 23.1.4.650

For now we monitor the server in hope that the new exclusion will work.

Time will tell

Ill make sure to reply again if we notice that the problem went away following the addition of SAP Machine to the exclusion, and thanks alot for the follow up!

**Comment by majoly83** [comment]
Good day.

Our issue is still sadly not resolved.

We attempted to add multiple exclusions on our SentinelOne so that it ignores sapmachine but also our sapcommerce directory but sadly no success.

We are still attempting to find a solution, once we get something more stable we will let you know.
