### ISSUE TITLE
Any plans for an official docker image of gradle bundled with sapmachine?

### ISSUE THREAD

**Issue by krodyrobi** [SAP/SapMachine#1510]
Currently [maven](https://hub.docker.com/layers/library/maven/3.9.4-sapmachine-21/images/sha256-277043a8c94539696ed5c1ce158ed614ffa3794f0bb2d5b671572c9ce93f58dc?context=explore) has an equivalent but not gradle.

Not sure if this is the proper repository to ask this but I assume you guys were a driver for maven as well.

**Comment by RealCLanger** [comment]
Hi @krodyrobi,

yes, the proper place to ask would be here I guess: https://github.com/keeganwitt/docker-gradle/issues. Doesn't look as if gradle images support different vendor JDKs, except for OpenJDK and GraalVM, but I guess one could ask. For Maven things are obviously different. But in fact, we weren't the people who requested SapMachine there, this came from outside our team.

Nevertheless, we'd welcome the addition. So, feel free (and endorsed) to ask the gradle image maintainers. 😄 

Cheers
Christoph
