### ISSUE TITLE
Fatal Error: G1ParScanThreadState::copy_to_survivor_space

### ISSUE THREAD

**Issue by D044500** [SAP/SapMachine#1520]
With https://jira.tools.sap/browse/PTS-1903 a user of the java-based tool SUPA has reported a fatal error occurred in
Java VM: OpenJDK 64-Bit Server VM SapMachine (11.0.18+10-LTS-sapmachine, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)

The corresponding hs_err file is attached.
IMHO the error relates to the G1GC as the problemtic frame is:
 V  [libjvm.so+0x797eb3]  G1ParScanThreadState::copy_to_survivor_space(InCSetState, oopDesc*, markOopDesc*)+0x43

Could you please take a look at it and give some advice on how we want to proceed here?
Many thanks, Sven

hs_err_pid81151.log(link removed)

**Comment by ansteiner** [comment]
Hi Sven,

please proceed as written in the mail to you.

Kind regards,
Andreas
