### ISSUE TITLE
SAP server connecting in Visual studio code

### ISSUE THREAD

**Issue by vykuntoasis** [SAP/SapMachine#1522]
Hi team,

Am able to connect sap server which is on cloud in Visual studio code.

But am unable to connect sap server of m organization in Visual studio code. The same sap server am able to add in Eclipse interface

Not sure how I can connect SAP server in Visual studio code .

Attached document shows the error information while connecting sap server

[error (1).docx](https://github.com/SAP/SapMachine/files/12923814/error.1.docx)

**Comment by RealCLanger** [comment]
Hi @vykuntoasis,

this issue seems in no way related to SapMachine, SAP's build of OpenJDK. Please find a better suiting channel to report problems for your SAP solution.

Thanks
Christoph
