### ISSUE TITLE
Issue with SapMachine for Java 1.8

### ISSUE THREAD

**Issue by xxLiuxx** [SAP/SapMachine#1523]
I've downloaded the Sap JVM 1.8 for Mac from this website (https://tools.hana.ondemand.com/#cloud), but it seems like the content structure for the zip is not the same as the ones in this repo.

I have Sap JVM 1.8, SapMachine 11, and 17 on my Mac. But when I run the command `/usr/libexec/java_home -V` to list all the JDKs, 1.8 can not be found.

Also to set Java_Home on Mac, we usually put something like `.../sapmachine-jdk-17.0.8.1.jdk/Contents/Home`. But in the JVM 1.8 folder, we don't have such directories.

Any idea on how to set the path for JVM 1.8 on Mac?

Thanks

**Comment by RealCLanger** [comment]
Hi @xxLiuxx,

that's right, we don't support an installation package for SAP JVM 8 on Mac, which would fulfil the criteria for deploying it to /Library/Java/JavaVirtualMachines. (At least not SAP-externally).
However, when you want to use the SAPJVM that you've downloaded from the location you've found, you can extract the zip file and then do `export JAVA_HOME=/<path to location where archive was extracted>/sapjvm_8`. After that a call to the java executable will pick up this installation. E.g. test via `java -version`.

BR
Christoph
