### ISSUE TITLE
Version 11.0.20

### ISSUE THREAD

**Issue by itscLx** [SAP/SapMachine#1546]
Hi there!

I was wondering if you could help me out. I'm trying to roll back to version 11.0.20 of a software using Homebrew, but I'm having trouble finding a release that works. Any suggestions?

Thanks a lot!

**Comment by RealCLanger** [comment]
Hi @itscLx,

I think the way we do handle SapMachine Homebrew Casks, it's only possible to update to the latest update version.

When you want to go back to an older SapMachine version, you have to download it from https://github.com/SAP/SapMachine/releases, e.g. extract the dmg and place it in /Library/JavaVirtualMachines.

Best regards
Christoph
