### ISSUE TITLE
Provide binaries for macOS

### ISSUE THREAD

**Issue by mpern** [SAP/SapMachine#155]
It would be nice if you could support macOS too, since quite a few devs use it and it's also a supported OS inside SAP.

**Comment by MSailer** [comment]
Hi Markus, 

MacOS is on its way, we are currently setting up the build infrastructure. So, have a little patience and stay tuned :)

Best,
Mitja

**Comment by MSailer** [comment]
Early Access release of Java 11 now available for MacOS: [https://sapmachine.io](https://sapmachine.io).
