### ISSUE TITLE
Can´t open Hana Studio in SUSE

### ISSUE THREAD

**Issue by arosas0022** [SAP/SapMachine#1568]
When I Launch SAP HANA Studio Launcher, an error txt is generate in /usr/sap/sdbstudio with the next information:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6c5c0b95e0, pid=26721, tid=26722
#
# JRE version: OpenJDK Runtime Environment SapMachine (11.0.8+10) (build 11.0.8+10-LTS-sapmachine)
# Java VM: OpenJDK 64-Bit Server VM SapMachine (11.0.8+10-LTS-sapmachine, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libglib-2.0.so.0+0x415e0]  g_str_hash+0x0
#
# Core dump will be written. Default location: Core dumps may be processed with "/bin/false" (or dumping to /usr/sap/hdbstudio/core.26721)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/SAP/SapMachine/issues/new
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Xmx1024m -Dfile.encoding=UTF-8 -Xms256m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djdk.http.auth.tunneling.disabledSchemes= /usr/sap/hdbstudio//plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /usr/sap/hdbstudio/hdbstudio -name Hdbstudio --launcher.library /usr/sap/hdbstudio//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.100.v20210209-1541/eclipse_11301.so -startup /usr/sap/hdbstudio//plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar --launcher.appendVmargs -exitdata 98003 -vm /usr/sap/hdbstudio//plugins/com.sap.ide.sapjvm.jre.linux.x86_64_110.8.0/jre/bin/java -vmargs -Xmx1024m -Dfile.encoding=UTF-8 -Xms256m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djdk.http.auth.tunneling.disabledSchemes= -jar /usr/sap/hdbstudio//plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar

Host: Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz, 16 cores, 123G, SUSE Linux Enterprise Server 15 SP3
Time: Fri Dec  8 16:51:43 2023 UTC elapsed time: 56 seconds (0d 0h 0m 56s)

**Comment by RealCLanger** [comment]
Hi @arosas0022,

this type of crash is likely related to the Hana DB Studio and no SapMachine (JDK) issue. Can you please open a ticket in their channels?

Thanks
Christoph
