### ISSUE TITLE
Implement a lean alternative for jcmd

### ISSUE THREAD

**Issue by schmelter-sap** [SAP/SapMachine#1593]
We often see usage of jcmd in (cloud) containers to get information needed for support. Since these environments tend to be configured with tight resources, it is important that the tool itself doesn't use much memory. Otherwise the container could be killed for exceeding its allowed memory usage. Since jcmd starts a whole JVM it would be nice to have a small native program which does mostly the same. One comfort feature which could be missing is specifying the connected VM by anything apart from a pid.

**Comment by simonis** [comment]
Looks like you want to take a look at the jattach utility which does exactly what you want (and a little more :)

https://github.com/jattach/jattach

**Comment by RealCLanger** [comment]
We now ship asprof with SapMachine and it has a built in jcmd feature.
