### ISSUE TITLE
How to pass password to "java" ?

### ISSUE THREAD

**Issue by mb13** [SAP/SapMachine#1595]
We are running the "java" from the "bin" folder in the following way:

`java -jar workbench.jar "http://some_mii_address:50000|myLoginName"`

and I'm asked for the password on each invocation of the above command. But how can I put the password as well? Is there any way? I tried with:

`type password.text | java -jar workbench.jar "http://some_mii_address:50000|myLoginName"`

or

`java -jar workbench.jar "http://some_mii_address:50000|myLoginName" < password.text`

where `password.text` is textfile with my password in the same directory. But it's not working.

**Comment by RealCLanger** [comment]
Hi,

that sounds like an issue of generic shell handling in connection with your application, nothing SapMachine specific. I can only recommend Google search/Stackoverflow/ChatGPT here 😄.

Cheers
Christoph
