### ISSUE TITLE
Wrong SAPMachine Version during Deployment to SAP BTP

### ISSUE THREAD

**Issue by Queenhymon** [SAP/SapMachine#1609]
**Context:**
We are trying to deploy a Java Spring Boot CAP application to deploy to BTP. During deployment we getting an issue with the SAPMachine Java version. (buildpack sap_java_buildpack is not working with service binding to PostgresDB, instead we use java_buildpack as advised by SAP)

**Log:**
Downloading Sap Machine JRE from https://github.com/SAP/SapMachine/releases/download/**sapmachine-11.0.21**/sapmachine-jre-11.0.21_linux-x64_bin.tar.gz

**We are expecting Sap Machine version 17 as configured:**
JBP_CONFIG_SAP_MACHINE_JRE: '{ use_offline_repository: false, version: 17.+ }'
parameters:
buildpack: java_buildpack
properties:
SPRING_PROFILES_ACTIVE: cloud,sandbox
JBP_CONFIG_COMPONENTS: "{jres: ['JavaBuildpack::Jre::SapMachineJRE']}"
JBP_CONFIG_OPEN_JDK_JRE: "{ jre: { version: 17.+ }}"
JBP_CONFIG_SAP_MACHINE_JRE: '{ use_offline_repository: false, version: 17.+ }'

**Error on BTP in the logs:**
java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by vtintillier** [comment]
You should use `JBP_CONFIG_SAP_MACHINE_JRE` instead of `JBP_CONFIG_OPEN_JDK_JRE` given you have selected SapMachine with `JBP_CONFIG_COMPONENTS`.

**Comment by RealCLanger** [comment]
Yes, as @vtintillier stated, change 
`JBP_CONFIG_OPEN_JDK_JRE: "{ jre: { version: 17.+ }}"`
to
JBP_CONFIG_SAP_MACHINE_JRE: "{ jre: { version: 17.+ }}"

You should probably also remove the line `JBP_CONFIG_SAP_MACHINE_JRE: '{ use_offline_repository: false, version: 17.+ }'` unless you want to pin to a specific JRE version. Then no download of SapMachine from GitHub during application staging phase is done.
