### ISSUE TITLE
Support lifetimes

### ISSUE THREAD

**Issue by jodastephen** [SAP/SapMachine#161]
I've added SapMachine to my [list](https://blog.joda.org/2018/09/time-to-look-beyond-oracles-jdk.html) of OpenJDK builds. Other builds have a [page](https://adoptopenjdk.net/support.html) describing how long each build will have security updates. Is there such a page/commitment for SapMachine? Thanks

**Comment by jodastephen** [comment]
A follow up question - does SapMachine pass the official testing compatibility kit (TCK) from the Java Community Process (JCP)? If it does, you need to say so on the website (or did I miss something?)

**Comment by MSailer** [comment]
Hi Stephen, 

thanks for adding us to your list of OpenJDK builds. I will compile some information about our support levels and will add to our [wiki](https://github.com/SAP/SapMachine/wiki) soon.

Yes, SapMachine does pass the official TCK. Java 10 has been tested on:
- x86 (64bit) / Ubuntu 14.04 LTS
- x86 (64bit) / Ubuntu 16.04 LTS

See also: https://github.com/SAP/SapMachine/wiki
Maybe we should publish this information somewhere more prominent?

For Java 11 further platforms will be supported (LinuxPPC Big/Little Endian, MacOS and Windows). These will also be verified by the TCK. 

Best,
Mitja

**Comment by jodastephen** [comment]
I hadn't seen the wiki - lots of good information there. I think you should add something to the home page, eg. "For more information see our wiki" with a suitable link.

The certification statement is great to see, but a little lacking in detail. Do you test every release? If not which builds/releases have been tested? Maybe this could be a table, or maybe a "TCK passed" piece of text could be added to each [release](https://github.com/SAP/SapMachine/releases).

Thanks

**Comment by simonis** [comment]
Hi Stephen,

thanks for mentioning us in your blog and for your suggestions regarding our home page and Wiki! @MSailer will follow up on this topic.

Concerning support, you're completely right -  support time frames for OpenJDK and all derived distributions are a tough question :) As you may know, even for LTS releases, Oracle has committed to support them in the OpenJDK with security fixes "for at least six month" only.

I think the plan of the various members (besides Oracle) in the OpenJDK community to support LTS releases like Java 11 for three or more years have to be seen more as a kind of "bet on the future". As long as nobody finally steps up and takes over the project leadership of the OpenJDK LTS update projects and guarantees to support them with security fixes, all promises of OpenJDK distributors who "just" build, test and distribute binaries based on the pure OpenJDK sources are a rather weak promise. I know that Red Hat and IBM have indicated their will to take over the project lead in the corresponding update projects but as far as I know there's no official commitment or guarantee from their side.

If nobody takes over responsibility for 8u and 11 LTS update and security releases within OpenJDK, there is of course still the possibility, that various parties do this themselves, in their own down-stream repositories. The problem with this approach would be that we would end up with several different releases with potential different set of security fixes and most probably different sets of fixed bugs and down-ported features. This will happen anyway for Oracle JDK and OpenJDK update releases after Oracle stops contributing to these projects (which is bad!).

Having said this, SapMachine will definitely be supported for at least as long as the corresponding OpenJDK upstream projects. Of course, we're also interested in supporting LTS releases three years and we may support them even longer, depending on our (i.e. SAP's) clients and internal stakeholders. 

Currently, SapMachine is not a stand-alone product for which you can buy support. Instead there are SAP products with well defined roadmaps and support time frames which depend on SapMachine. So in the end, we will support SapMachine as long as required by these stake holders. We will communicate and adapt these dates as soon as the corresponding product road maps are finalized.

Hopefully, this clarifies your questions. Thanks for your understanding,
Volker

**Comment by MSailer** [comment]
@jodastephen: Finally, I have added a wiki page describing security updates, maintenance and support process

**Comment by jodastephen** [comment]
Blog updated with a link
