### ISSUE TITLE
WinOnARM64 version for SapMachine not available

### ISSUE THREAD

**Issue by billgatesfan** [SAP/SapMachine#1659]
It seems MS released a compiled ARM64 version of the OpenJDK : https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-21. 

Is there a similar place, where I can download the SapMachine, that is natively compiled on ARM64, and that I can deploy as an app on ARM64 Windows11 devices?    I could not find anything on the main page (https://sap.github.io/SapMachine/).

**Comment by RealCLanger** [comment]
Support for Windows/ARM64 is not on our current roadmap, so there are no plans. However, if you can help us with a business case for this platform in the SAP context, we can honor this in our planning.

**Comment by billgatesfan** [comment]
Our company plans to release ARM64 platform (Snapdragon X Elite) with Windows11 to our employees...whenever it will be made available by major laptop manufacturers. The idea is to have as much ARM64 native binaries as possible, so that we do not rely on the x64 emulation layer.

**Comment by RealCLanger** [comment]
I can imagine adding that support some time when such hardware becomes more mainstream and more OpenJDK vendors support it.

**Comment by skateball** [comment]
Hi @billgatesfan 
is Windows On ARM64 still from relevance for you?
The currently existing SapMachine-WinX64 builds works fine on a Windows on ARM64. 
Regards Christian
