### ISSUE TITLE
Version 11.0.23 adds ubuntu user and group

### ISSUE THREAD

**Issue by Nereboss** [SAP/SapMachine#1675]
Updating from version 11.0.22 to version 11.0.23 adds new ubuntu user and group.

In our Dockerfile, we create a user 1000:1000 to not run as admin. In the updated version this leads to errors, as the group 1000 already exists.

Im wondering why such a change happened in a patch update.
Was it a bug previously that the user was not created and the behaviour in 11.0.23 is how it was intended?
Is this a new bug that was introduced in 11.023?

---

Using `RUN echo $(cat /etc/passwd)` and `RUN echo $(getent group)` the users and groups can be printed which results in the following:

For 11.0.22 (no ubuntu user/group):

users:
```root:x:0:0:root:/root:/bin/bash daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin bin:x:2:2:bin:/bin:/usr/sbin/nologin sys:x:3:3:sys:/dev:/usr/sbin/nologin sync:x:4:65534:sync:/bin:/bin/sync games:x:5:60:games:/usr/games:/usr/sbin/nologin man:x:6:12:man:/var/cache/man:/usr/sbin/nologin lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin mail:x:8:8:mail:/var/mail:/usr/sbin/nologin news:x:9:9:news:/var/spool/news:/usr/sbin/nologin uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin proxy:x:13:13:proxy:/bin:/usr/sbin/nologin www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin backup:x:34:34:backup:/var/backups:/usr/sbin/nologin list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin _apt:x:100:65534::/nonexistent:/usr/sbin/nologin```

groups:
```root:x:0: daemon:x:1: bin:x:2: sys:x:3: adm:x:4: tty:x:5: disk:x:6: lp:x:7: mail:x:8: news:x:9: uucp:x:10: man:x:12: proxy:x:13: kmem:x:15: dialout:x:20: fax:x:21: voice:x:22: cdrom:x:24: floppy:x:25: tape:x:26: sudo:x:27: audio:x:29: dip:x:30: www-data:x:33: backup:x:34: operator:x:37: list:x:38: irc:x:39: src:x:40: gnats:x:41: shadow:x:42: utmp:x:43: video:x:44: sasl:x:45: plugdev:x:46: staff:x:50: games:x:60: users:x:100: nogroup:x:65534:```

For 11.0.23 (has ubuntu user/group):

users:
```root:x:0:0:root:/root:/bin/bash daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin bin:x:2:2:bin:/bin:/usr/sbin/nologin sys:x:3:3:sys:/dev:/usr/sbin/nologin sync:x:4:65534:sync:/bin:/bin/sync games:x:5:60:games:/usr/games:/usr/sbin/nologin man:x:6:12:man:/var/cache/man:/usr/sbin/nologin lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin mail:x:8:8:mail:/var/mail:/usr/sbin/nologin news:x:9:9:news:/var/spool/news:/usr/sbin/nologin uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin proxy:x:13:13:proxy:/bin:/usr/sbin/nologin www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin backup:x:34:34:backup:/var/backups:/usr/sbin/nologin list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin _apt:x:42:65534::/nonexistent:/usr/sbin/nologin nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash```

groups:
```root:x:0: daemon:x:1: bin:x:2: sys:x:3: adm:x:4:ubuntu tty:x:5: disk:x:6: lp:x:7: mail:x:8: news:x:9: uucp:x:10: man:x:12: proxy:x:13: kmem:x:15: dialout:x:20:ubuntu fax:x:21: voice:x:22: cdrom:x:24:ubuntu floppy:x:25:ubuntu tape:x:26: sudo:x:27:ubuntu audio:x:29:ubuntu dip:x:30:ubuntu www-data:x:33: backup:x:34: operator:x:37: list:x:38: irc:x:39: src:x:40: shadow:x:42: utmp:x:43: video:x:44:ubuntu sasl:x:45: plugdev:x:46:ubuntu staff:x:50: games:x:60: users:x:100: nogroup:x:65534: ubuntu:x:1000:```

**Comment by RealCLanger** [comment]
Hi,

I believe that has nothing to do with SapMachine 11.0.22->11.0.23 but with the underlying base image. If you use `FROM sapmachine:11` in your dockerfile, you now get an image based on Ubuntu 24.04 instead of Ubuntu 22.0.4.

If you want to still use Ubuntu 22.0.4 based images, you can use `FROM sapmachine:11-ubuntu-22.0.4` or another tag from [11-ubuntu-jammy, 11-ubuntu-22.04, 11.0.23-ubuntu-jammy, 11.0.23-ubuntu-22.04, 11-jdk-ubuntu-jammy, 11-jdk-ubuntu-22.04, 11.0.23-jdk-ubuntu-jammy, 11.0.23-jdk-ubuntu-22.04](https://github.com/SAP/SapMachine-infrastructure/blob/05efe26bea6456dc7e561c6d601b2132f6bae6f2/dockerfiles/official/11/ubuntu/22_04/jdk/Dockerfile)

Please let us know if that helps.

Cheers
Christoph

**Comment by nicolabeghin** [comment]
If useful when using the `ubuntu-24.04` images: just remove the pre-existing `ubuntu` user in your `Dockerfile` as per https://bugs.launchpad.net/cloud-images/+bug/2005129/comments/2

    userdel -r ubuntu
