### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000003040019

### ISSUE THREAD

**Issue by Paulofangy** [SAP/SapMachine#1678]
One of my client machines is encountering an Access Violation Exception when running SAP Customer Checkout version 2.12.28. This issue has been observed with both SapMachine versions 11.0.19 and 11.0.22.

Can anyone suggest any debugging steps or troubleshooting tips to identify the root cause of this issue, or a way to fix this?

[hs_err_pid3084.log](https://github.com/SAP/SapMachine/files/15404399/hs_err_pid3084.log)

Thanks in advance for your assistance!

**Comment by MBaesken** [comment]
I think "SAP Customer Checkout" is an SAP software so please open an SAP ticket for further analysis of the issue.

Thanks, Matthias
