### ISSUE TITLE
Add installation support via SDKMan

### ISSUE THREAD

**Issue by danielqo** [SAP/SapMachine#168]
SDKMan (https://sdkman.io/) allows you to install and manage different versions of JDKs (and other Java-related tools) via CLI, the same way RVM does for Ruby. They have a well-documented procedure describing how to add development kits and their versions to it at https://sdkman.io/vendors. 

Supporting installation via SDKMan may increase SAPMachine popularity and adoption outside SAP customer base, which would help improve the product itself.

**Comment by simonis** [comment]
Hi Daniel,

thanks for your suggestion and sorry for the late response. I must confess that I didn't knew SDKMan before. I've had a brief look at it and it looks quite interesting. Unfortunately, supporting SDKMan is not our highest priority, but as this is a true open source project we will be more than happy to accept any contributions on this topic.

Thank you and best regards,
Volker

**Comment by MSailer** [comment]
Support request for SDKMan popped up again: https://twitter.com/robinjayasinghe/status/1095390966465339392

**Comment by rjayasinghe** [comment]
SDKMAN has good doku on how to contribute new candidates. I'll have a look in the next days. :)

**Comment by marc0der** [comment]
I've had a quick look at your archives for Linux, Mac and Windows and they are all in the right format (so no changes needed on your side). All that is required is a PR on our [database migrations](https://github.com/sdkman/sdkman-db-migrations) project.

Here is an [example](https://github.com/sdkman/sdkman-db-migrations/commit/09f6990068bc2b1382fe4eea228db7f2610c087d) of how to write one of these if that helps.

We will need to come up with a distribution suffix for your JDKs. I'd propose something like `sap`, `sapm` or `sapmchn`. wdyt? In other words, the version string will look something like `11.0.2-sapm` when you do an `sdk ls java`.

**Comment by MSailer** [comment]
Thanks for your assistance @marc0der! I have just filed a [PR](https://github.com/sdkman/sdkman-db-migrations/pull/68).

**Comment by marc0der** [comment]
It's a great pleasure! I've left a few comments but will merge as soon as those are addressed.

**Comment by rjayasinghe** [comment]
Awesome! 😎

**Comment by MSailer** [comment]
> It's a great pleasure! I've left a few comments but will merge as soon as those are addressed.

Your help was much appreciated, and happy to be on board of sdkman!

**Comment by MSailer** [comment]
@danielqo: sdkman now [offers](https://github.com/sdkman/sdkman-db-migrations/pull/68) 
SapMachine. Hence, closing this again.
