### ISSUE TITLE
Brew error with sapmachine21-jre

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/SapMachine#1855]
Hi team,

while updating my sapmachine21-jre installation to version 21.0.5 using brew, I received the error 

```
==> Purging files for version 21.0.5 of Cask sapmachine21-jre
Error: sap/sapmachine/sapmachine21-jre: It seems the Generic Artifact source '/Library/Java/JavaVirtualMachines/sapmachine-21.jre' is not there.
```

After several attempts of fixing it, I stumbled unto [this advice](https://stackoverflow.com/questions/63136571/updating-cask-generic-artifact-source-not-found) to disable the macOS's Gatekeeper with the flag:

```
brew reinstall --cask --no-quarantine sapmachine21-jre
```

My superficial understanding of this is that the software might be unsigned or improperly signed. Could you please have a look?

**Comment by RealCLanger** [comment]
Hi @JenniferStamm,

to me this looks like some other package manager (or the SapMachine installer) messed around with this installation. To get it clean from brew perspective I think you'll need to remove and then install again, e.g. by:
`brew remove sapmachine-21.jre`
`brew install sapmachine-21.jre`
Maybe you even need the option `-f` for brew remove.

If it is the SapMachine Manager that is interfering here, you should either completely remove the brew package and let SapMachine Manager handle the installation or you should disable automatic updates in the Settings of SapMachine Manager.

Best regards,
Christoph

**Comment by JenniferStamm** [comment]
Hi @RealCLanger ,

ah, sorry, I thought I had tried that. 

Your command wasn't correct, but following the suggestion in the error message got me a successful installation without using quarantine 👍 

```
~ brew install sapmachine-21.jre
[...]
Warning: No available formula with the name "sapmachine-21.jre".
==> Searching for similarly named formulae and casks...
==> Casks
sap/sapmachine/sapmachine21-jre                                                                           sapmachine-jdk

To install sap/sapmachine/sapmachine21-jre, run:
  brew install --cask sap/sapmachine/sapmachine21-jre
```

**Comment by RealCLanger** [comment]
> Hi @RealCLanger ,
> 
> ah, sorry, I thought I had tried that.
> 
> Your command wasn't correct, but following the suggestion in the error message got me a successful installation without using quarantine 👍
> 
> ```
> ~ brew install sapmachine-21.jre
> [...]
> Warning: No available formula with the name "sapmachine-21.jre".
> ==> Searching for similarly named formulae and casks...
> ==> Casks
> sap/sapmachine/sapmachine21-jre                                                                           sapmachine-jdk
> 
> To install sap/sapmachine/sapmachine21-jre, run:
>   brew install --cask sap/sapmachine/sapmachine21-jre
> ```

OK, glad it is solved. Yes, it should have been brew install sapmachine21-jre. 😄
