### ISSUE TITLE
Remove Alpine Linux documentation from Readme

### ISSUE THREAD

**Issue by reshnm** [SAP/SapMachine#187]
There are still some reference to Alpine Linux left in the README.md.
These should be removed.

**Comment by lenkite** [comment]
Why has Alpine Linux references been removed ? Does sapmachine no longer support alpine linux  ?

**Comment by MSailer** [comment]
> Why has Alpine Linux references been removed ? Does sapmachine no longer support alpine linux ?

We currently don't have active stakeholders for alpine linux, therefore we decided to remove it for the time being.
