### ISSUE TITLE
A minimal solution to start child processes in an own process group (*nix only)

### ISSUE THREAD

**Issue by tstuefe** [SAP/SapMachine#203]
A new switch is added, -Dsap.jdk.lang.Process.createNewProcessGroupsOnSpawn. If this switch is set to true, new processes started with ProcessBuilder.start or with Runtime.exec() will be leader of an own process group instead of belonging to the process group of the parent VM.

**Comment by RealCLanger** [comment]
Closing issue manually as it is only fixed in sapmachine11 branch.
