### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by demarco88** [SAP/SapMachine#211]
Hi. More a question than a defect....:
Is it allowed for firms (f.e. SAP partners) to deliver the SapMachine jre (bundelt) with their product (as private jre) without loosing their commerical rights? Or must they deliver on GPL (with copyleft)?
Thanks for the Information
Marco

**Comment by simonis** [comment]
SapMachine (like OpenJDK) is licensed under the GPL plus Classpath Exception (see http://openjdk.java.net/legal/gplv2+ce.html). This allows you to bundle SapMachine with your product without getting "infected" by the viral nature of the GPL.
So as long as you are using the complete SapMachine as a JDK/JRE you can easily bundle it with your product and license your product however you like. This may change if you copy and paste single classes from SapMachine/OpenJDK, but that's anyway not your use case, as far as I understood.
