### ISSUE TITLE
Improve dt_filesocket implementation

### ISSUE THREAD

**Issue by schmelter-sap** [SAP/SapMachine#235]
The dt_filesocket debug transport in the sapmachine11 repository needs a few improvemts:

- A jtreg test
- A mechanism to avoid leaving file socket files behind
- Checking the connected user and not just relying on the file permissions. This is needed since on some platforms the connection permission is taken form the permission of the directory in which the domain sockets is created. Additionally it will be easier later to support abstract domain socket on unix later, since they cannot rely on file permissions at all.
@

**Comment by RealCLanger** [comment]
pushed to sapmachine11 branch
