### ISSUE TITLE
CFBundleName should indicate this is SapMachine

### ISSUE THREAD

**Issue by ryenus** [SAP/SapMachine#351]
This seems to be some unfinished part of #320.

Running `/usr/libexec/java_home -V` on macOS (10.14), we can see the following

```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    11.0.2, x86_64:	"OpenJDK 11.0.2"	/Library/Java/JavaVirtualMachines/sapmachine-jdk-11.0.2.jdk/Contents/Home
    11.0.2, x86_64:	"OpenJDK 11.0.2"	/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
    11.0.2, x86_64:	"Amazon Corretto 11"	/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
```

Here **`OpenJDK 11.0.2`** for sapmachine-jdk-11.0.2.jdk should be something like `SapMachine 11.0.2` or maybe "SapMachine 11`, as in Amazon Corretto 11.

**Comment by RealCLanger** [comment]
Hi,

thanks for opening this issue. I'm currently looking into things for Mac, so I'll tackle this :)

Best regards
Christoph

**Comment by ryenus** [comment]
It seems the bundle name and a few other variables ultimately point to `MACOSX_BUNDLE_NAME_BASE=OpenJDK`, which is from 
https://github.com/SAP/SapMachine/blob/d58ba44b16bf63aac6f60d03a8f0051d64a0b1fe/make/autoconf/version-numbers#L45

Probably the solution is to change it to `MACOSX_BUNDLE_NAME_BASE=SapMachine`?
