### ISSUE TITLE
wiki Installation SDKMan wrong version

### ISSUE THREAD

**Issue by zzebastien** [SAP/SapMachine#415]
In this page: https://github.com/SAP/SapMachine/wiki/Installation, for the section "Installation with SDKMAN!"
Instead of:
`sdk install java 11.03.sapmchn`
Please replace by (a dot is missing between 0 and 3):
`sdk install java 11.0.3-sapmchn`

**Comment by RealCLanger** [comment]
Thanks for reporting this. I updated the Wiki. Let me know if something is still not correct.
