### ISSUE TITLE
sapmachine-jdk can't be opened on macOS 10.15 Beta (Catalina)

### ISSUE THREAD

**Issue by choas** [SAP/SapMachine#422]
On macOS 10.15 Beta (Catalina) I've downloaded SAPmachine 11.0.3 and unzipped it to /Library/Java/JavaVirtualMachines

running ```java -version``` shows this message:

> “sapmachine-jdk-11.0.3.jdk” can’t be opened because it is from an unidentified developer.
> Your security preferences allow installation of only apps from the App Store and identified developers.
> Safari downloaded this file today at 13:51 from github-production-release-asset-2e65be.s3.amazonaws.com.

macOS 10.15 requires Notarization

**Comment by MSailer** [comment]
Hey Lars, 

thanks for reporting this issue. I will check it and get back to you soon.

Cheers,
Mitja

**Comment by reshnm** [comment]
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by reshnm** [comment]
@choas Hi, just wanted to let you know that we are still actively working on this issue.

**Comment by reshnm** [comment]
We have added a documentation of the current state of notarization an SapMachine on macOS Catalina.

https://github.com/SAP/SapMachine/wiki/Installation#mac-osx-1015-catalina

**Comment by niemda** [comment]
Seems like Homebrew cask installation is affected by quarantine. This can be fixing by removing the com.apple.quarantine xattr after the installation.

**Comment by reshnm** [comment]
@niemda  You can use the `--no-quarantine` for brew which removes the attribute automatically.

`brew cask install --no-quarantine sapmachine-jdk`
