### ISSUE TITLE
Provide logo as SVG

### ISSUE THREAD

**Issue by emilianbold** [SAP/SapMachine#451]
The logo you have at https://sap.github.io/SapMachine/assets/images/logo_circular.png is pretty neat but it's a PNG that has to be (manually) scaled.

A SVG image would be much nicer.

I'm trying to use this logo on www.jChoice.eu where other OpenJDK distributions do have SVG logos.

**Comment by MSailer** [comment]
Hi @emilianbold, 

just a quick update...haven't forgotten about your request, it only takes us some time to provide the SVG, but will do so soon :) 
Keep you posted!

Thanks for having us at jChoice!

**Comment by emilianbold** [comment]
The logo looks quite vectorial to me so I assume it's a matter of being in
a non-SVG format.

No hurry, thanks for the update.

--emi

**Comment by MSailer** [comment]
Hi @emilianbold,

finally, we have the svg version of our logo. Please check out:
https://sap.github.io/SapMachine/assets/images/logo_circular.svg

Maybe, this one would also look nice:
https://sap.github.io/SapMachine/assets/images/logo_circular_url.svg

Thanks again for having us on your list :)

**Comment by emilianbold** [comment]
Thank you! I've updated the icon on jchoice.eu

--emi
