### ISSUE TITLE
Is there a SAPMachine version that uses Java 10 or Java 9? 

### ISSUE THREAD

**Issue by tomcheah** [SAP/SapMachine#484]
Is there a SAPMachine version that uses Java 10 or Java 9? 

If yes, what version number is it and how would I install it? I'm trying to build a docker image using it. 

Currently, I use "FROM sapmachine:11". 

I found this repo: https://github.com/SAP/SapMachine/releases/tag/sapmachine-10.0.2

I believe SAPMachine 10 uses Java 10. But I'm unsure how to install it. "FROM sapmachine:10.0.2" on my Dockerfile didn't work.

**Comment by MSailer** [comment]
Hi Tom,

well, the thing is, Java 10 has run out of support and has been succeeded by Java 11. May I ask why you would want to use Java 10 instead of Java 11?

**Comment by tomcheah** [comment]
Java 11 removes java.xml.bind packages, whereas those packages are just deprecated on Java 10. 

The project I'm currently working on uses Java 8 which supports those packages. Without those packages, the service literally will not run. I understand that the system needs to be modernized, but for now, I'm looking for a solution where I can use a SAPMachine version that uses Java 10. 

I see the existence of SAPMachine 10 which uses Java 10, but I'm struggling to create an image from it on my Dockerfile.

**Comment by reshnm** [comment]
Why not use the JAXB library?

https://github.com/eclipse-ee4j/jaxb-ri
