### ISSUE TITLE
JVM Crash when upload Photo in smartedit.

### ISSUE THREAD

**Issue by tonyjafar** [SAP/SapMachine#487]
hello,

we get recently the error "V [libjvm.so+0xcf2a79] ResolvedMethodTable::add_method(Handle)+0x49 " wehn we trying to upload an image to Smartedit in Hybris, the JVM crashed and restarted. 

Stactrace:
`
INFO   | jvm 1    | main    | 2019/08/22 08:43:17.345 | INFO  [ajp-nio-8010-exec-3] [10.196.218.251] [LoginFormComposer] Available UI locales for backoffice: [de, en, es, es_CO, fr, it, ja, ko, pt, ru, zh, zh_TW, hi, id, cs, pl, hu]
INFO   | jvm 1    | main    | 2019/08/22 08:43:25.954 | WARN  [ajp-nio-8010-exec-2] [10.196.218.251] [DefaultAbstractCollectorChartHandler] Could not find series values
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | #
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | # A fatal error has been detected by the Java Runtime Environment:
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | #
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | #  SIGSEGV (0xb) at pc=0x00007f5c47d9a609, pid=11541, tid=12244
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | #
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | # JRE version: OpenJDK Runtime Environment (11.0.3+7) (build 11.0.3+7-LTS-sapmachine)
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | # Java VM: OpenJDK 64-Bit Server VM (11.0.3+7-LTS-sapmachine, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | # Problematic frame:
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | # V  [libjvm.so+0xcb4609]  ResolvedMethodTable::add_method(Handle)+0x49
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | #
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | #
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | # An error report file with more information is saved as:
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.737 | # /opt/store/hybris/bin/platform/tomcat/bin/hs_err_pid11541.log
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.838 | #
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.838 | # If you would like to submit a bug report, please visit:
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.838 | #   https://github.com/SAP/SapMachine/issues/new
INFO   | jvm 1    | main    | 2019/08/22 08:44:41.838 | #
STATUS | wrapper  | main    | 2019/08/22 08:44:41.992 | JVM received a signal UNKNOWN (6).
STATUS | wrapper  | main    | 2019/08/22 08:44:41.992 | JVM process is gone.
ERROR  | wrapper  | main    | 2019/08/22 08:44:41.992 | JVM exited unexpectedly.
STATUS | wrapper  | main    | 2019/08/22 08:44:42.394 | Reloading Wrapper configuration...
STATUS | wrapper  | main    | 2019/08/22 08:44:42.599 | Launching a JVM...
`

Javasap Version:
`
openjdk 11.0.3 2019-04-17 LTS
OpenJDK Runtime Environment (build 11.0.3+7-LTS-sapmachine)
OpenJDK 64-Bit Server VM (build 11.0.3+7-LTS-sapmachine, mixed mode)
`

**Comment by RealCLanger** [comment]
Hi Tony,

thanks for reporting this bug with SapMachine.

What we need to follow up on this would probably be the hs_err file. E.g. /opt/store/hybris/bin/platform/tomcat/bin/hs_err_pid11541.log as mentioned in your log.

Can you share this? You can add it here or also send it to me, e.g. via email.

Thanks
Christoph

**Comment by tonyjafar** [comment]
[hs_err_pid27676.log](https://github.com/SAP/SapMachine/files/3549933/hs_err_pid27676.log)
Hi @RealCLanger here is the log file, Thanks.

**Comment by TheRealMDoerr** [comment]
Hi,
this seems to be the issue https://bugs.openjdk.java.net/browse/JDK-8210457 which was fixed in 11.0.4.

**Comment by tonyjafar** [comment]
Will update Java and try again, then will update this issue. Thanks

**Comment by RealCLanger** [comment]
Thanks for finding this, @TheRealMDoerr.

@tonyjafar, I'll close this issue. Feel free to re-open if you still observe it in 11.0.4.
