### ISSUE TITLE
Various improvements to vitals

### ISSUE THREAD

**Issue by tstuefe** [SAP/SapMachine#492]
This is an umbrella issue for a number of improvements to the *vitals* feature:

1) consistently name the "comma-separated-value" output feature "csv" (it was erroneously named "cvs" in the initial commit).

2) Make it possible to reverse the printing order in the historic tables. Now, the default is we print the samples youngest-to-oldest. That is inconvenient, especially for processing in csv form. Add an option to VM.vitals to optionally reverse that order.

3) When printing comma-separated-values, enclose them in quotes. That prevents localization issues if LC_NUMERIC is not en_US.

4) The "scale" option of VM.vitals should accept bytes, aka 1, to get precise values for automated processing. This would also be consistent with what NMT does.

5) A new option should be added, "-XX:[+-]DumpVitalsAtExit" (off by default) which should dump the vitals history both in textual and csv form when the VM exits.

6) The existing "raw" output option for VM.vitals is currently only enabled on debug builds. However, it is useful in general and I would like to have it in release builds as well.

(Note: all this is supposed to be backported to our older releases).

**Comment by RealCLanger** [comment]
Reopened, because the thing needs to be brought to SapMachine 13 and 11.

**Comment by RealCLanger** [comment]
Fixes have been merged to sapmachine11, sapmachine13 and sapmachine. Hence, closing this.
