### ISSUE TITLE
NPE when you compile code with Jrebel running with Hybris Server instance of 1905

### ISSUE THREAD

**Issue by puravrustagi** [SAP/SapMachine#519]
the Issue is coming with 11.0.3 version of sapmachine  

  [java] java.lang.NullPointerException
     [java] 	at java.management/javax.management.remote.JMXServiceURL.<init>(JMXServiceURL.java:148)
     [java] 	at de.hybris.platform.jmx.JmxClient.restartWrapper(JmxClient.java:275)
     [java] 	at de.hybris.platform.jmx.JmxClient.restartWrapper(JmxClient.java:257)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [java] 	at bsh.Reflect.invokeMethod(Reflect.java:131)
     [java] 	at bsh.Reflect.invokeStaticMethod(Reflect.java:95)
     [java] 	at bsh.Name.invokeMethod(Name.java:868)
     [java] 	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:69)
     [java] 	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:96)
     [java] 	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:41)
     [java] 	at bsh.Interpreter.eval(Interpreter.java:659)
     [java] 	at bsh.Interpreter.eval(Interpreter.java:750)
     [java] 	at bsh.Interpreter.eval(Interpreter.java:739)
     [java] 	at de.hybris.platform.util.ClientExecuter.execute(ClientExecuter.java:49)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [java] 	at de.hybris.bootstrap.loader.Loader.execute(Loader.java:143)
     [java] 	at de.hybris.bootstrap.loader.Loader.main(Loader.java:117)

**Comment by RealCLanger** [comment]
Hi,

from looking at the code of JMXServiceURL, I can see that the incoming parameter String serviceURL from de.hybris.platform.jmx.JmxClient.restartWrapper(JmxClient.java:275) must be null at that place. That's the only thing I can take out of the stacktrace.

Are you an SAP internal from hybris, working in development? Then you should probably contact me (Christoph Langer) directly and we can exchange more information and log files.

Otherwise, if you are a customer, you should probably contact Hybris support with this issue. They'll have a look and contact the JDK team if necessary.

Thanks
Christoph

**Comment by puravrustagi** [comment]
Hi Chris,

Let me know what more information you need from me on the ticket for its resolution.

Regards,

Purav Rustagi
Senior Technical Consultant, Expert Services India
SAP Customer Experience
purav.rustagi@sap.com<mailto:purav.rustagi@sap.com>
Cell: +91 9599109633

SAP India Pvt Ltd
2nd Floor, Wing-B, Block –A,
122002 Gurgaon, Haryana, India

**Comment by RealCLanger** [comment]
Hi Purav,

as we're in direct contact now, I'm closing this issue. Should we find out anything general about SapMachine with this, I'll update the Github issue later on.

Thanks
Christoph
