### ISSUE TITLE
Unrecognized VM option 'PrintGCTimeStamps' Error: Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by harsimransingh1992** [SAP/SapMachine#554]
I'm using sapmachine-jdk-11.0.5 version for SAP hybris development, while migration process from down releases. the JVM is unable to start. 
Unrecognized VM option 'PrintGCTimeStamps'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
JVM exited while loading the application.

**Comment by RealCLanger** [comment]
Hi,

the flag PrintGCTimeStamps has been removed together with others via bug https://bugs.openjdk.java.net/browse/JDK-8145092 in JDK9. It is the implementation of JEP 271: "Unified GC Logging" (https://openjdk.java.net/jeps/271). So for JDK11 you should read the JEP and adjust your gc logging settings accordingly.

Best regards
Christoph
