### ISSUE TITLE
Never used variable 'result ‘

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/SapMachine#559]
https://github.com/SAP/SapMachine/blob/9ad67aeda369723b655b6b0d22dc5a1790a1786d/src/hotspot/share/compiler/compilerOracle.cpp#L383

**Comment by RealCLanger** [comment]
Hi @QiAnXinCodeSafe,

I guess you have a point here. Would it be possible for you to raise this issue with OpenJDK?

Cheers
Christoph

**Comment by RealCLanger** [comment]
Hi again,

my colleague @MBaesken has opened a bug for this in OpenJDK: https://bugs.openjdk.java.net/browse/JDK-8235489
He'll also follow up on fixing this and potentially backporting to OpenJDK11.

With that information, I'm closing this issue. Please track the OpenJDK bug. In case you've got questions or something doesn't progress in your sense, feel free to open this issue.

Best regards
Christoph
