### ISSUE TITLE
Private static method reflection/introspection is failing from 11.0.5 to 11.0.6 

### ISSUE THREAD

**Issue by mmanna-sapfgl** [SAP/SapMachine#602]
We have some legacy code that tests a private static method using reflection. When we downloaded 11.0.5 a while back, this test was passing. With 11.0.6 it's failing. Everything else is working fine.

Is this an expected behaviour. We understand that private member access by reflection/introspection is discouraged, but should we expect this change between minor version changes?

**Comment by reshnm** [comment]
Hi @mmanna-sapfgl, could you provide us a small code sample, which triggers the described behavior (working on 11.0.5, failing on 11.0.6)?

**Comment by MBaesken** [comment]
I suppose this is not a specific SapMachine issue, but also an issue in OpenJDK 11.0.6 .
So I would propose you send us a small code sample showing the issue (like reshnm suggested) and then we check and open a bug in the OpenJDK bug system and bring the issue up on the OpenJDK mailing list.

**Comment by RealCLanger** [comment]
Since we didn't get a reaction to our comments for a while, I'm closing the issue. Feel free to reopen if you have additional information.
