### ISSUE TITLE
French (Switzerland) formatting seems to be broken

### ISSUE THREAD

**Issue by rseidlnc** [SAP/SapMachine#615]
hey!

we're currently using this version of sap machine in our project:

openjdk 11.0.6 2020-01-15 LTS
OpenJDK Runtime Environment (build 11.0.6+10-LTS-sapmachine)
OpenJDK 64-Bit Server VM (build 11.0.6+10-LTS-sapmachine, mixed mode)

when I execute the following code:

```
Double value = 1000000.4;
NumberFormat format = NumberFormat.getInstance(new Locale("fr", "CH"));
format.setMinimumFractionDigits(2);
System.out.println(format.format(value))
```
I get this output:

- expected fr_CH: 1'000'000,40 vs. actual 1 000 000,40
- expected de_CH: 1'000'000,40 vs. actual 1'000'000,40
- expected it_CH: 1'000'000,40 vs. actual 1'000'000,40

In our opinion the output of fr_CH should be equals to de_CH and it_CH. Maybe this issue is related to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8132125

**Comment by reshnm** [comment]
Hi @rseidlnc, thank you for reporting this issue.
Browsing the OpenJDK Bug Database I found the following:

> Please refer : http://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html#JDK-8008577
> From JDK 9 and above, the default locale data uses data derived from the Unicode Consortium's Common Locale Data Repository (CLDR). So there are changes with respect to some locales and hence this exception.
> For ex. In the fr_CH locale, the decimal grouping separator is Non-breaking space character , whereas it used to be ' in JRE(COMPAT).
> 
> Refer: https://www.unicode.org/cldr/charts/29/by_type/numbers.symbols.html#a1ef41eaeb6982d
> 
> To use the JRE locale with JDK 9 and above set java.locale.providers to a value with COMPAT ahead of CLDR. :
> -Djava.locale.providers=COMPAT, CLDR 

Could you test whether setting the mentioned property works for you?

**Comment by RealCLanger** [comment]
Hi,

I'm closing this issue as @reshnm 's comment is probably the explanation and provides a workaround/fix. Feel free to reopen, if you have further questions or additional information.

Cheers
Christoph

**Comment by rseidlnc** [comment]
Hi @reshnm @RealCLanger ,

thanks for the reply! The property -Djava.locale.providers=COMPAT,CLDR is by default already set like this: "tomcat.generaloptions=-Djava.locale.providers=COMPAT,CLDR..." by SAP Commerce, however I still see the strange behavior described above.

Cheers,
Rafael

**Comment by RealCLanger** [comment]
OK, I'm reopening the issue then. We'll have a closer look.

**Comment by rseidlnc** [comment]
@RealCLanger thanks!

**Comment by picpromusic** [comment]
It seems to be there is an error in the CLDR-dataset. At the CLDR-Chart for numbers and symbols (https://www.unicode.org/cldr/charts/29/by_type/numbers.symbols.html#a1ef41eaeb6982d) there is no entry for fr_CH. It matches to the information in the current(36.1 from 2020-03-11) CLDR-Download. There are multiple tickets in various states at https://unicode-org.atlassian.net/projects/CLDR/issues/?filter=allissues&orderby=priority%20DESC&keyword=fr_CH . @rseidlnc Would you like to report/discuss there too.

**Comment by RealCLanger** [comment]
Hi @rseidlnc

Does this issue still persist?

I will close the issue for now but please feel free to tell me otherwise.
