### ISSUE TITLE
Backport request [to 11] - 8214418: half-closed SSLEngine status may cause application dead loop

### ISSUE THREAD

**Issue by jhult** [SAP/SapMachine#618]
I don't have access to bugs.openjdk.java.net.

Any chance someone could submit an upstream request to backport JDK-8214418 to 11?

https://github.com/SAP/SapMachine/commit/67a0d5bbea2ddbd420ae4fc4fe3070ede2716b91
https://hg.openjdk.java.net/jdk/jdk13/rev/5022a4915fe9
https://bugs.openjdk.java.net/browse/JDK-8240071

**Comment by RealCLanger** [comment]
Hi Jonathan,

at a first glance, this looks suitable for a backport. The bug ticket https://bugs.openjdk.java.net/browse/JDK-8240071 seems to be closed, that is, only Oracle employees can see the details. However, when having a first glance at the change, I guess this is a candidate for backport.

I'll get back to you after some more work on this.

Best regards
Christoph

**Comment by jhult** [comment]
Thank you so much for the fast and detailed response.

**Comment by MBaesken** [comment]
I backported the change to jdk11u-dev , see
 https://hg.openjdk.java.net/jdk-updates/jdk11u-dev/rev/6852be0de227
So most likely the change will go into OpenJDK 11.0.8 .

**Comment by jhult** [comment]
Awesome. Thank you!

**Comment by bhuvangu** [comment]
How can the original issue be reproduced?

**Comment by jhult** [comment]
I originally bumped into this using Atlassian Jira (see [this issue](https://jira.atlassian.com/browse/JRASERVER-70780)).
