### ISSUE TITLE
Maintaining a current version | Auto Update process

### ISSUE THREAD

**Issue by GiantCrocodile** [SAP/SapMachine#639]
Hello,

I was seeking for information on how to maintain a current version of SapMachine 11 (LTS) on client devices, e. g. different notebook models with Windows 10 or MacOS. During my research I wasn't able to find an auto updater as we know it from previously typical Java setups provided by Oracle. Can you provide us with more information on how to easily make sure that the SapMachine installation is up2date and will be maintained properly without afford from an end user? This is a requirement for compliance and IT-security confirmatory.

Thank you for your help!

Best Regards,

**Comment by MSailer** [comment]
Hi there,

thanks for getting in touch. I'm afraid there is no "auto update" feature for SapMachine yet and I'm not sure whether we want to introduce one. Currently it's not planned. 
So, for the time being you would have to check manually for new releases (I understand this is not nice). The most important security updates are released in sync with the OpenJDK security updates release schedule, i.e. 4 times a year. 

On MacOS and Linux/Unix you could try to use sdkman, homebrew (MacOS only) or the operating system's package manager to assist you with the update. I'm sure, however, you are aware of this, but's not 100% what you are looking for :) 

Best,
Mitja

**Comment by GiantCrocodile** [comment]
Hi @MSailer!

Our main issue here is that we don't talk about like five clients but hundreds of clients and we have to provide a solution for this as it's unlikely that every employee will take care of this properly as it's easy to forget about a software like this: Nobody see's this software in action as it just executes some stuff and stays in the background. We talked to one of our IT providers which rolls out standard software updates via a special software to all of our clients but they told us that they won't support OpenJDK nor SapMachine as it's not requested often enough by other customers.

I will pass your feedback to a colleague and we will see what we can do here. This is quite a major issue for a medium or big sized company.

Thank you for your reply!

**Comment by MSailer** [comment]
Hi @GiantCrocodile,

yes, I see your point. I also thought about asking you, how you manage other software products, some that also don't have an "auto-update" feature. Now I know. It's a pity your IT provider doesn't support OpenJDK/SapMachine and I wonder what Java runtime they offer instead? Not offering Java at all would be kind of a surprise. Anyway, this surely something to be sort out by you and your IT provider :) 
From the company I work for I know IT also has their own means to manage client software and it didn't seem to be a big thing for them to add SapMachine. For them it was just one more MSI package in their catalog.

Still, sorry, that I have no solution for you at the moment.

**Comment by GiantCrocodile** [comment]
Hi @MSailer! I will pass your feedback to my colleague. I agree that it's an interesting decision by the IT provider. I will ask my colleagues if and which Java runtime they do support. My colleagues are evaluating if we can automate this ourself.

Thank you for your help!

**Comment by MSailer** [comment]
@GiantCrocodile, I will close this now, please re-open if needed.
