### ISSUE TITLE
It's not possible to create an new System Connection to HANA Tenant Database

### ISSUE THREAD

**Issue by harry2303** [SAP/SapMachine#643]
![image](https://user-images.githubusercontent.com/26458802/80984097-b5068f80-8e2d-11ea-86e3-536210d4acc7.png)
In Eclipse IDE:
With sapmachine as JVM a error occurs - (attached screenshot)
With Oracle JRE the same connection to the same HANA tenant database with the same connection parameters will be created without errors

Details to used sapmachine version:
java.runtime.version=11.0.7+10-LTS-sapmachine
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.vendor=SAP SE
java.vendor.url=https://sapmachine.io/

**Comment by MSailer** [comment]
Hi Harry,

sounds like you have stumbled across [JEP 320](http://openjdk.java.net/jeps/320). Could you check which version of the Oracle JDK you use to run your Eclise? I suppose it is not Java 11, but some earlier version. 

Anyways, Eclipse does support Java 11, but support also depends on the Eclipse version you use. So you might want to check this as well.

**Comment by mevlakhov** [comment]
Hi, I'm also have that problem. 
I try change SDK on jdk14.0.1, but nothing change.

**Comment by mevlakhov** [comment]
I'm resolve problem. Install JDK 8 update 251 for x64 from oracle. Write this JDK in eclipse.ini and add JRE in preference (Java -JRE).

**Comment by harry2303** [comment]
Hi,
thanks for your answers.
If i use JRE 8 update 251, no problem occurs. It's a problem of the JVM sapmachine (in version 11.0.7+10-LTS-sapmachine) as i described above. My idea/my attempt was to use sapmachine (11.0.7+10-LTS-sapmachine) as jvm for eclipse (2019-12). 
kind regards, Harry

**Comment by reshnm** [comment]
Hi @harry2303,

as @MSailer already mentioned, the package javax.xml.soap was removed with Java 11 and so with SapMachine 11.

It seems that HANA Studio is not working on Java versions newer than 8.

https://answers.sap.com/questions/698488/eclipse-photon-connection-to-hana-express.html

So I guess the only solution is to use a JDK 8.

Kind regards
Rene

**Comment by harry2303** [comment]
Hi Rene,
thanks for clarification...
Finally I've understood the first answer on my issue.

Kind regards,
Harald

**Comment by RealCLanger** [comment]
As this seems to be understood, I'm closing the issue.

**Comment by harry2303** [comment]
:-) SAPmachine without 100% support for SAP HANA Development Tools 
Thanks for closing....

**Comment by RealCLanger** [comment]
> :-) SAPmachine without 100% support for SAP HANA Development Tools
> Thanks for closing....

Yes, that's a bit unfortunate... but I guess that's something the HANA Development Tools would have to fix. It won't work with any JDK11.
