### ISSUE TITLE
Certification

### ISSUE THREAD

**Issue by alittlec** [SAP/SapMachine#665]
Hi,

How do we certify a platform for running SAPMachine?
Can you provide contact details?

**Comment by RealCLanger** [comment]
Hi Alec,

I don't fully understand your request.

As for certification: We do certify SapMachine against the Java Compatibility Kit (JCK), as documented here: https://github.com/SAP/SapMachine/wiki/Certification-and-Java-Compatibility

For you as a customer/user, there is no mandatory certification necessary to use SapMachine. At least not from our side. :) So, could you please give some more details on your requirement?

Best regards
Christoph

**Comment by RealCLanger** [comment]
Hi,

as I think you are in direct contact with my team, I'm closing this issue.

Cheers
Christoph
