### ISSUE TITLE
brew cask install <major> version cask missing

### ISSUE THREAD

**Issue by rufreakde** [SAP/SapMachine#667]
When following your install guide and trying to install the long term support 11 version it does not work.
examles:
```
brew cask install sapmachine11-jdk
brew cask install sapmachine13-ea-jdk
````
It seems the only cask that exists is sapmachine-jdk and currently installs version 14.

**Comment by RealCLanger** [comment]
Hi @rufreakde,

I guess you followed https://github.com/SAP/SapMachine/wiki/Installation#-macos, right?

There we write:

Homebrew supports the installation of the latest released SapMachine by default:
brew cask install sapmachine-jdk

However, you might want to install other versions, such as early access builds of releases/updates currently in development or older versions of a certain Java release, e.g. SapMachine 11 LTS. For this you can use this tap.

Tap it via:
brew tap sap/sapmachine

So, you are right when you say "the only cask that exists is sapmachine-jdk and currently installs version 14." This is true for the default brew installation. All the other casks have to be tapped first (brew tap sap/sapmachine).

Makes sense?

Cheers
Christoph

**Comment by reshnm** [comment]
I think this has been answered. Closing for now.

**Comment by rufreakde** [comment]
Yes, my mistake for not taping into the other repo. @RealCLanger
