### ISSUE TITLE
RPM installation fails on CentOS 7

### ISSUE THREAD

**Issue by Hatelix** [SAP/SapMachine#670]
Hello there!

I tried to install the current release RPM package of the SapMachine 11 (sapmachine-jdk-11.0.7-1.x86_64.rpm) with yum on a machine running on CentOS 7. It failed with the following error message:

```
ERROR You need to update rpm to handle:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by sapmachine-jdk-14.0.1-1.x86_64
RPM needs to be updated
```

I searched for a solution for this issue and have found that the compression algorithm used for RPM packages in Fedora 31 was changed recently from xz to zstd (see [here](https://fedoraproject.org/wiki/Changes/Switch_RPMs_to_zstd_compression)) which is probably why this error occurs. The machine I'm trying to install the SapMachine to runs on "CentOS Linux release 7.8.2003 (Core)" and its software packages are up-to-date. This means:
```
yum.noarch                      3.4.3-167.el7.centos
rpm.x86_64                      4.11.3-43.el7
rpm-libs.x86_64                 4.11.3-43.el7
```
I also tried it with the current release RPM of the SapMachine 14 (sapmachine-jdk-14.0.1-1.x86_64.rpm) yielding the same result.

I assume the release RPM packages of the SapMachine are assembled using the zstd compression?

It would be great if you could provide alternative RPM packages for operating systems that do not support the new default compression. For now, my only option is to install the SapMachine manually with the provided archive, which is not a very clean solution.

**Comment by reshnm** [comment]
Hi @Hatelix, thank you for reaching out.
Please see the answer of #658

**Comment by Hatelix** [comment]
Hi @reshnm and thank you very much, I didn't see that!
