### ISSUE TITLE
jstat -class option man doc typo

### ISSUE THREAD

**Issue by Bambooin** [SAP/SapMachine#687]
https://github.com/SAP/SapMachine/blob/3dc278d911f4f241fea755289cf15c98430894be/src/jdk.jcmd/share/man/jstat.1#L227

Bytes: Number of KB loaded. --> Bytes: Number of KB unloaded.

refer: https://github.com/AdoptOpenJDK/openjdk-jdk/issues/3

**Comment by RealCLanger** [comment]
Hi,
looks like a minor fix. I'll take care of it upstream.
Cheers
Christoph

**Comment by Bambooin** [comment]
It's nice, that you can help.

Actually I already report it to upstream mail list, follow Martijn Verburg's advice

https://github.com/AdoptOpenJDK/openjdk-jdk/issues/3

But the mail is being held for approve, you can refer it after it's approved.

Is being held until the list moderator can review it for approval.
The reason it is being held:
    Post by non-member to a members-only list

The mail subject is:
Java 14 jstat -class option man doc typo

**Comment by RealCLanger** [comment]
Hi,

as per https://mail.openjdk.java.net/pipermail/serviceability-dev/2020-July/032292.html, this will need to be handled in OpenJDK by Oracle folks. So I'm closing this issue. I guess the mailing list is also the right place to follow up.

Best regards
Christoph

**Comment by Bambooin** [comment]
Hi,

  Thanks for you help, the bug is already filed by David.
  Mailing list and [openjdk jira](https://bugs.openjdk.java.net/browse/JDK-8249450) is the place to follow.

Thanks.
