### ISSUE TITLE
Windows msi update to new version

### ISSUE THREAD

**Issue by uwe42** [SAP/SapMachine#692]
Hi, 
it would be nice if the MSI package could update to a newer version of SapMachine. 
ATM we have to uninstall the old version before we are able to install the new version. 

If the installer would replace the old installation would simplify the update process.

**Comment by reshnm** [comment]
Hi @uwe42 unfortunately this is not possible with minor version upgrades and Windows msi installer packages.
We would need to do a .exe installer with more complex logic to implement such functionality.
