### ISSUE TITLE
SapMachine JDK 11.0.8 release for macOS has malfunctioning disk image

### ISSUE THREAD

**Issue by rtrouton** [SAP/SapMachine#694]
The disk image linked below will not mount, which indicates a problem with the disk image:

https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.8/sapmachine-jdk-11.0.8_osx-x64_bin.dmg

![Screen Shot 2020-07-20 at 10 13 34 AM](https://user-images.githubusercontent.com/618055/87947765-cbf27080-ca71-11ea-9ce1-ac8b8f8a2444.png)

**Comment by RealCLanger** [comment]
This is weird. I can reproduce it, though it installs fine via brew - from the very same image.

**Comment by reshnm** [comment]
Hi @rtrouton thanks for pointing this out. I will re-upload the disk image.
