### ISSUE TITLE
SapMachine : For PI Process Integration tool

### ISSUE THREAD

**Issue by blueesh001** [SAP/SapMachine#711]
Hello ,
We tried to use SapMachine java to launch PI Process Integration tool on Win 10 machine but is not working. .JNLP file is not launching. We are on NW 7.5
Does it support this NW version.

Regards, Nilesh

**Comment by reshnm** [comment]
Hi @blueesh001 

Java Web Start has been removed with Java 11. This is why your JNLP file is not launching.
See https://adoptopenjdk.net/migration.html#icedtea-web as a possible migration path.
Currently we are not providing official support for Java Web Start with SapMachine.

Best Regards,
Rene

**Comment by MSailer** [comment]
I will close this request, feel fine to re-open in case you have further questions, etc.
