### ISSUE TITLE
Unable to open JNLP file from PI System

### ISSUE THREAD

**Issue by dharm910** [SAP/SapMachine#720]
Unable to open JNLP file downloaded from SAP PI system using below version on windows 10. 

openjdk version "11.0.8" 2020-07-15 LTS
OpenJDK Runtime Environment SapMachine (build 11.0.8+10-LTS-sapmachine)
OpenJDK 64-Bit Server VM SapMachine (build 11.0.8+10-LTS-sapmachine, mixed mode)

**Comment by RealCLanger** [comment]
Hi @dharm910,

generally, Java Web Start is a deprecated technology and is only supported in Oracle JDK 8. In higher releases (Oracle, OpenJDK >8 and also SapMachine which is only available >8), it is not included any more. There exists a project called Iced Tea Web which can be used as a replacement (https://github.com/AdoptOpenJDK/IcedTea-Web, https://adoptopenjdk.net/icedtea-web.html). However, it's not completely a drop-in replacement and one would have to check with the application on whether this is supported.

So I guess this is rather a case where you should open a support ticket with SAP PI. If you do, you might send me a reference and I can help with following up.

Best regards
Christoph

**Comment by yamadamn** [comment]
Hi @dharm910 ,
You can use OpenWebStart (https://openwebstart.com/) based on IcedTea-web.
It can be used with JDK 11 release (maybe include SapMachine).

**Comment by MSailer** [comment]
@dharm910 feel free to re-open, if you have additional questions :)
