### ISSUE TITLE
SIGSEGV _ZN20G1ParScanThreadState9update_rsIjEEvP10HeapRegionPT_P7oopDesc when using java sapgui

### ISSUE THREAD

**Issue by agueriot** [SAP/SapMachine#743]
I got the following error when I try to compile SAP Commerce 2005 with custom extensions:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000105530f08, pid=76231, tid=36355
#
# JRE version: OpenJDK Runtime Environment SapMachine (11.0.8+10) (build 11.0.8+10-LTS-sapmachine)
# Java VM: OpenJDK 64-Bit Server VM SapMachine (11.0.8+10-LTS-sapmachine, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# V  [libjvm.dylib+0x330f08]  _ZN20G1ParScanThreadState9update_rsIjEEvP10HeapRegionPT_P7oopDesc+0x34
```

I could reproduce the error by compiling again executing `ant all`. Then I tried to compile with another JDK (AdoptOpenJDK 11) using the `ant clean all` command and it worked without error. I switched back to SapMachine and ran `ant clean all`, it did not crash. I tried `ant all`, it did not crash. It looks like this crash happens only in very specific situations.

Attached error log [hs_err_pid76231.log](https://github.com/SAP/SapMachine/files/5430972/hs_err_pid76231.log)

**Comment by marcellourbani** [comment]
happens to me all the time with the official build on archlinux

**Comment by tstuefe** [comment]
@marcellourbani  Same stack trace? Can you please provide the hs-err file (at least cut/paste the stack trace)?

**Comment by marcellourbani** [comment]
@tstuefe not sure the stack trace is the same, and can't reproduce it right now.

these logs should be identical, but just in case...

[hs_err_pid392825.log](https://github.com/SAP/SapMachine/files/6356622/hs_err_pid392825.log)
[hs_err_pid393820.log](https://github.com/SAP/SapMachine/files/6356623/hs_err_pid393820.log)

PS: I only use sapmachine as a part of SAPGUI java installation, didn't know anything about these logfiles

**Comment by MBaesken** [comment]
those crashes look a little bit similar to this one 
https://bugs.openjdk.java.net/browse/JDK-8218266

JDK-8218266 : G1 crash in AccessInternal::PostRuntimeDispatch

**Comment by MBaesken** [comment]
The SAPGUI developers told use there is an issue in older versions in the AGI (ApplicationGuiInterface);
they recommend updating to  7.70 rev 03 / 7.50 rev 13 . If  this update  does not make  the issue disappear , switching to another GC  than G1 might be a possible workaround.
The GUI devs told us  this command line parameter in guilogon (LINUX) .
