### ISSUE TITLE
Error: Unrecognized VM option 'ShenandoahGCHeuristics=compact'

### ISSUE THREAD

**Issue by Satya758** [SAP/SapMachine#744]
Hi,

We are using SAPMachine JRE in CF [Sap Machine JRE 11.0.9_0.0.b0](https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.9/sapmachine-jre-11.0.9_linux-x64_bin.tar.gz). 

Enabling or adding Shenandoah GC options results in the following error

 `2020-10-24T22:09:24.49+0530 [APP/PROC/WEB/0] ERR Unrecognized VM option 'UseShenandoahGC'
   2020-10-24T22:09:24.49+0530 [APP/PROC/WEB/0] ERR Error: Could not create the Java Virtual Machine.
   2020-10-24T22:09:24.49+0530 [APP/PROC/WEB/0] ERR Error: A fatal exception has occurred. Program will exit.`

Is Shenandoah supported in SAPMachine?

**Comment by RealCLanger** [comment]
Hi @Satya758,

we did not yet enable Shenandoah for SapMachine 11.0.9. We're currently in discussion if and when we'll activate this feature. I'll update this ticket once we have a decision.

Best regards
Christoph

**Comment by TheRealMDoerr** [comment]
Note: It's available in SapMachine 17.

**Comment by RealCLanger** [comment]
To conclude this ticket: There are currently no plans to enable Shenandoah GC in SapMachine 11. The way to go to use this feature is to move forward to SapMachine 17 where several improvements and fixes have been made to it anyway.

However, if anybody has a strong (SAP) case why they really need it, don't hesitate to contact us and we might reconsider.
