### ISSUE TITLE
Long-Term Support for SapMachine

### ISSUE THREAD

**Issue by Tarkleigh** [SAP/SapMachine#745]
Hey everyone,

in my organization there are considerations to upgrade from the old SAP JDK 8 to SapMachine 11 LTS to get the new Java 11 features but there have been concerns about the long term support. According to your documentation, 11 LTS is supported until 2022 which is much shorter than SAP JDK 8 which - if I remember correctly - is supported until 2028. This is a real issue for our IT organization. Are there plans for a new LTS version which is maintained longer? Or is this the new normal?

Thanks and best regards

**Comment by MSailer** [comment]
Hi @Tarkleigh,

thanks for getting in touch. You can find more details about the new release cadence and maintenance strategy in the wiki:
https://github.com/SAP/SapMachine/wiki/Security-Updates,-Maintenance-and-Support

In a nutshell: 
- Every three years there will be a Long Term Supported (LTS) release. Java 17 (GA 09/2021) will be our next LTS release.
- LTS releases will be supported for at least four years. So, there is one year time to adopt the new LTS. 

I hope this helps and suits your plans. Let us know if you have any concerns or other expectations.

**Comment by Tarkleigh** [comment]
Hi @MSailer 

thanks for the information. The primary concern of IT was that it does not make sense to upgrade to 11 in the coming months as it will only be supported for one more year. Maybe going to the 17 version will convince them, though this is a rather big version leap. In general, I think SapMachine would be well advised to make its support cycles at least as long as OpenJDK (who support Java 11 until 2024, see https://access.redhat.com/articles/1299013) or even the old SAP JDK which it supposedly replaces.

As a developer myself, I understand how difficult these long support windows can be but I think it is vital for the acceptance of SapMachine that it offers similar support windows as its predecessor or at least as openJDK. Otherwise it might be hard for it to get traction in the enterprise world.

Best regards,
Tarkleigh

**Comment by RealCLanger** [comment]
Hi Tarkleigh,

first of alI let me put one thing in the correct context here: The RedHat article that you cited (https://access.redhat.com/articles/1299013) is not "The" official statement about how long OpenJDK 11 will be supported, It is just the statement of the company RedHat, on how long they intend to support OpenJDK11. But there might be other parties or vendors that might keep OpenJDK11 alive beyond that date.

Having said that, it is well possible that we'll also extend the support statement for SapMachine 11. (But no promises ;-)) I personally agree with your point that it might ease the decision for potential adopters to have a longer committed period of support. So, to help the internal discussion, maybe you can share some more details about your company/use case for SapMachine 11. Maybe in a personal message?

Thanks & Best regards
Christoph

**Comment by Tarkleigh** [comment]
Hi Christoph,

thanks I will send you a message,

Best regards,
Tarkleigh

**Comment by RealCLanger** [comment]
Hi,
I'm closing this issue as we've started some direct conversation. Feel free to comment or reopen in case there's anything to be added here.
Cheers
Christoph
