### ISSUE TITLE
Add `-ea` to tag for 16 and 17 EA

### ISSUE THREAD

**Issue by eddumelendez** [SAP/SapMachine#787]
Currently, tags for 16 and 17 Early Access (EA) from https://sap.github.io/SapMachine/assets/data/sapmachine_releases.json are displayed `"tag": "sapmachine-17+1"`. Can you add the `.ea` so the tag can looks like `sapmachine-17-ea+1`?

This will be very helpful in order to automate them and publish them at sdkman.

See [this](https://github.com/eddumelendez/sdkman-java-migrations/blob/master/src/sdkman_java_migrations/sap_machine.clj)

**Comment by RealCLanger** [comment]
Hi Eddu,

sorry for the late reply to your inquiry.

Changing tag semantics is always a very delicate thing to do as further automation is built on top of it. This happens not only in our infrastructure, somethimes it is out of our control. SDKMan is a good example for that. With that in mind, we are very reluctant to change here.

Having said that, I also don't understand where the big benefit for the script that you pointed to would be. Please forgive my ignorance :) However, as for the current SapMachine tag format you can be sure that all tags containing a '+<build number>' part (e.g. scan for the plus sign) are ea builds. Our release builds don't contain the build tags any more but distinguish theirselves only by the 5 digit java version number.

With that comment I'll close this issue but feel free to ask further questions or give more background why we should consider this.

Best regards
Christoph
