### ISSUE TITLE
Method will not be inlined warning/error

### ISSUE THREAD

**Issue by vtintillier** [SAP/SapMachine#788]
With version `11.0.9.1_windows-x64`, I get those three lines each time I start a Java process:

```
Compiler intrinsic is defined for method [java.lang.Math.abs(I)I], but the method is not annotated with @HotSpotIntrinsicCandidate. Method will not be inlined.
Compiler intrinsic is defined for method [java.lang.Math.abs(J)J], but the method is not annotated with @HotSpotIntrinsicCandidate. Method will not be inlined.
Compiler intrinsic is defined for method [java.lang.Math.abs(F)F], but the method is not annotated with @HotSpotIntrinsicCandidate. Method will not be inlined.
```

Here is my `java -version` output for example:

```
$ java -version
Compiler intrinsic is defined for method [java.lang.Math.abs(I)I], but the method is not annotated with @HotSpotIntrinsicCandidate. Method will not be inlined.
Compiler intrinsic is defined for method [java.lang.Math.abs(J)J], but the method is not annotated with @HotSpotIntrinsicCandidate. Method will not be inlined.
Compiler intrinsic is defined for method [java.lang.Math.abs(F)F], but the method is not annotated with @HotSpotIntrinsicCandidate. Method will not be inlined.
openjdk version "11.0.8" 2020-07-15 LTS
OpenJDK Runtime Environment SapMachine (build 11.0.8+10-LTS-sapmachine)
OpenJDK 64-Bit Server VM SapMachine (build 11.0.9.1+1-LTS-sapmachine, mixed mode)
```

**Comment by RealCLanger** [comment]
Hi Vivien,

the output of your java -version looks weird, indeed.

It should rather be:
openjdk version "11.0.9.1" 2020-11-05 LTS
OpenJDK Runtime Environment SapMachine (build 11.0.9.1+1-LTS-sapmachine)
OpenJDK 64-Bit Server VM SapMachine (build 11.0.9.1+1-LTS-sapmachine, mixed mode)

It looks a bit like you have a SapMachine 11.0.8 with a hotspot VM 11.0.9.1.

What's your operating system? How did you install the VM?

Cheers
Christoph

**Comment by vtintillier** [comment]
Hi Christoph

I checked again with version downloaded myself, and it works fine. So it is more an issue with an auto-installed version by SAP IT. Will contact you internally for that.

Sorry for the trouble.
