### ISSUE TITLE
macOS installation instructions for brew need to be updated

### ISSUE THREAD

**Issue by gregorwolf** [SAP/SapMachine#795]
Hello SapMachine Team,

with [Homebrew 2.5.0](https://brew.sh/2020/09/08/homebrew-2.5.0/) the `brew cask install` command was deprecated. The wiki page https://github.com/SAP/SapMachine/wiki/Installation#-macos should be updated accordingly.

Best regards
Gregor

**Comment by MSailer** [comment]
Hi Gregor,

thanks for spotting this! I have updated documentation accordingly and also referred to the latest install script of Homebrew. Feel free to re-open this issue if anything would be missing :) 

Bye Bye
