### ISSUE TITLE
Question: SapMachine and ARM CPU Platform (Aarch64, ARM64, ARMv8, Apple Silicon, AWS Graviton) 

### ISSUE THREAD

**Issue by Cyclenerd** [SAP/SapMachine#810]
TL;DR: Will there be an ARM version?

I (and I'm sure others) would be interested to know if an ARM version is planned? Apple is currently switching to ARM. So many developers will soon be using ARM. I also see more and more Macbooks among SAP employees.

I would appreciate a short info and maybe more details about the SAP strategy.

Thank you 👍 

I also posted the question on the SAP Platform for such questions:
https://answers.sap.com/questions/13107725/sap-and-arm-cpu-platform-aarch64-arm64-armv8-apple.html

**Comment by MSailer** [comment]
Hi Nils,

thanks for getting in touch. We currently only have a "beta" release of SapMachine [1] for aarch64. 

If and when aarch64 becomes an officially supported platform of SapMachine is still an ongoing discussion. Unfortunately, I don't know yet when a final decision will be taken and I'm not in a position to share information about SAP's overall strategy. Your request, however, helps us to better understand the demand and I will refer to it in our ongoing discussions. 

Maybe we can keep this issue and I'll update it as soon as I have any news?

[1] https://github.com/SAP/SapMachine/releases/download/sapmachine-17%2B7/sapmachine-jdk-17-eabeta.7_linux-aarch64_bin.tar.gz

**Comment by Cyclenerd** [comment]
Thank you for the information. Feel free to leave this issue open. I am always happy to receive more news.

**Comment by MSailer** [comment]
Hi Nils,

I just wanted to let you know, that our current planning is to support Apple Silicon/M1 with SapMachine 17, due in September 2021. Hope this helps!

**Comment by Cyclenerd** [comment]
This is great news. I will close this issue.

**Comment by eklass** [comment]
Hello @MSailer,
Is there any plan, that SAP also provides Apple Silicon/M1 Support for Sap Machine 11?
Thank you in advance for your feedback.

**Comment by RealCLanger** [comment]
> Hello @MSailer, Is there any plan, that SAP also provides Apple Silicon/M1 Support for Sap Machine 11? Thank you in advance for your feedback.

See: https://github.com/SAP/SapMachine/issues/925#issuecomment-991107331

**Comment by ylupol** [comment]
@MSailer, sorry for asking this off-topic question in this thread.

Do you have any info when [SAP JCo](https://support.sap.com/en/product/connectors/jco.html#section) will support Apple M1 (arm64e) architecture?

**Comment by ylupol** [comment]
@mtolksdorf, thank you!

**Comment by nicolabeghin** [comment]
As far as I can see, as of today SapMachine for `aarch64` is available from https://sap.github.io/SapMachine/

![image](https://user-images.githubusercontent.com/2743637/162917028-dd9d6be2-2a1e-416f-ac88-3a824176545b.png)

It's not available as a Docker image yet from DockerHub ref. https://hub.docker.com/_/sapmachine

**Comment by RealCLanger** [comment]
Yes, there is a MacOS aarch64 build but it's still considered a beta. Once it's an official release, we'll also provide a docker image.

**Comment by fdmeregildo** [comment]
Have a error when jco initialization. "JCo initialization failed with java.lang.UnsatisfiedLinkError: no sapjco3 in java.library.path" Someone have a found a solution?

**Comment by nice2mitja** [comment]
@fdmeregildo, see comment here for a workaround, while SAP JCo is not available on aarch64: https://github.com/SAP/SapMachine/issues/1237#issuecomment-1237997398

**Comment by nicolabeghin** [comment]
FYI in june 2023 SAP JCO 3.1.8 has been released for Linux AARCH64 (ARM64) support ref. https://me.sap.com/notes/3347894 - this opens the way to using **dockerized** SAP Commerce with JCO under Mac ARM64! 

<img width="942" alt="image" src="https://github.com/SAP/SapMachine/assets/2743637/870c8729-f86d-4ea9-ae0e-92a591e67be6">
