### ISSUE TITLE
Can't install SapMachine using SDKMAN on macOS

### ISSUE THREAD

**Issue by zonkil** [SAP/SapMachine#846]
Installation of SapMachine is broken. 

```Downloaded binary to: /Users/i341699/.sdkman/tmp/java-15.0.2-sapmchn.bin
Get post-installation hook: https://api.sdkman.io/2/hooks/post/java/15.0.2-sapmchn/darwinx64
Copy remote post-installation hook: /Users/i341699/.sdkman/tmp/hook_post_java_15.0.2-sapmchn.sh
A Mac OSX post-install hook was found for Java 15.0.2-sapmchn-openjdk.
Download has failed, aborting!

Can not install java 15.0.2-sapmchn at this time...
```

In this post installation hook: https://api.sdkman.io/2/hooks/post/java/15.0.2-sapmchn/darwinx64
function **__sdkman_validate_binary_input** is failing

**Comment by RealCLanger** [comment]
Hi @zonkil,

I think this issue should be reported with SDKMAN: https://github.com/sdkman/sdkman-cli/issues

I'm hence closing this one.

Cheers
Christoph
