### ISSUE TITLE
SapMachine 11.0.10 to 11.0.11 removing TLSv1 and TLSv1.1 support

### ISSUE THREAD

**Issue by nicolabeghin** [SAP/SapMachine#854]
Hi everyone
when upgrading SapMachine from 11.0.10 to 11.0.11 the TLSv1 and TLSv1.1 TLS protocols are marked as disabled, leading to issues with CPQ libraries when connecting to MySQL (it's not possible to pass JDBC parameter `useSSL=false` in the CPQ DB endpoints).
> javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

This is because of the change in `/usr/lib/jvm/sapmachine-11/conf/security/java.security` from 11.0.10 to 11.0.11:
> jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1

![image](https://user-images.githubusercontent.com/2743637/117122597-59e7df80-ad96-11eb-8448-cd6858bf435c.png)

**Comment by nicolabeghin** [comment]
If using SapMachine's official Docker images, it can be enabled back with this additional `Dockerfile` line

`RUN sed -i 's/jdk\.tls\.disabledAlgorithms=SSLv3, TLSv1, TLSv1\.1/jdk\.tls\.disabledAlgorithms=SSLv3/' $JAVA_HOME/conf/security/java.security
`

**Comment by RealCLanger** [comment]
Hi Nicola,

yes, this works as expected. SAP JVM is following the Java Crypto Roadmap with disabling TLSv1.0 and TLSv1.1: https://java.com/en/jre-jdk-cryptoroadmap.html

So if you need those protocols you have to manually enable it again, e.g. like you describe for the Docker Image.

Please let me know if something is still unclear or you see any blocking issues with this.

Best regards
Christoph

**Comment by nicolabeghin** [comment]
Thanks @RealCLanger it's not our requirement per-se, it's SAP-provided CPQ libraries that do not allow to pass over JDBC `useSSL=false` therefore forcing to enable back the TLSv1/1.1 protocol to avoid being cut out of the database due to the SSL handshake failing.

https://help.sap.com/viewer/50c996852b32456c96d3161a95544cdb/1905/en-US/0f6cea48c35243cc829ff225e1fe71fb.html

![image](https://user-images.githubusercontent.com/2743637/117137177-9ffa6e80-ada9-11eb-8068-2ca87746d0c0.png)

**Comment by RealCLanger** [comment]
Hm, I don't fully understand it. Does that mean the databse is not running TLSv1.2 or TLSv1.3? Can't that be enabled which should be the best way to solve this?

Other than that, if there's a JDBC property that could be passed, I guess you should open up a request for the CPQ/SSC libraries to support that?
