### ISSUE TITLE
Missing CA in cert-store: Sectigo

### ISSUE THREAD

**Issue by 749** [SAP/SapMachine#863]
The Sectigo Certificate Authority is not recognized within the docker image: https://hub.docker.com/_/sapmachine
Please add it to the java keystore.

**Comment by ppawel** [comment]
I think Let's Encrypt CA is also not recognized, there is not DST certificate in the keystore...

**Comment by RealCLanger** [comment]
Hi,
just a short update on this issue. SapMachine currently only ships the OpenJDK set of root certificates plus one root CA from SAP. We're currently looking whether we can/should extend this list.

As for letsencrypt: There is letsencryptisrgx1. But that isn't what you mean, @ppawel ?

Best regards
Christoph

**Comment by ppawel** [comment]
In my case, it was actually a different problem that I had with certificates, so everything looks fine in SAP Machine wrt Let's Encrypt.

**Comment by RealCLanger** [comment]
I'm closing this ticket as it has been inactive for a while. However, feel free to post here again if you still have an issue (that we from SapMachine might be able to solve).
