### ISSUE TITLE
Loading SapMachine fails

### ISSUE THREAD

**Issue by alexklassenkps** [SAP/SapMachine#887]
Dear SapMachine Team!

Is there currently an issue with getting SapMachine through http://dist.sapmachine.io/debian/amd64 ?

Getting suddenly the following error while trying to download.
"The repository 'http://dist.sapmachine.io/debian/amd64 ./ Release' does not have a Release file."

TIA
Alex

**Comment by RealCLanger** [comment]
Hi Alex,

at the moment we have some infrastructure issue with the package repository. We're working on fixing this.

Sorry for the inconvenience, stay tuned.

Cheers
Christoph

**Comment by alexklassenkps** [comment]
Hi Christoph,

thanks for the response. Hope you can fix it soon! 
Please let us know as soon as that is fixed, it breaks a lot of build chains I guess.

TIA
Alex

**Comment by GeraldGrote** [comment]
Can confirm.  The Lets Encrypt Certificate for dist.sapmachine.io expired yesterday.

Our Pipelines are failing because of it.

**Comment by aiboogie** [comment]
hello, thanks for the update.
would you have an additional url for the deb repo (that we could add until this is solved) ?

ans some proposals :)
- could using cloudflare be an alternative to lets encrypt? That would offer a perpetual certificate
- would it be possible to mirror the deb repo to ubuntu/debian repos such that in the future we could switch pulling the deb file from there?

thank you,
Bogdan.

**Comment by RealCLanger** [comment]
Hi,

we think we have fixed it now. Can you please test and let us know whether you still see issues?

Thanks
Christoph

**Comment by aiboogie** [comment]
seems to work, thanks!

**Comment by GeraldGrote** [comment]
yes, works. Thank you

**Comment by alexklassenkps** [comment]
fixed!

**Comment by RealCLanger** [comment]
Great, I'm closing this issue then. Sorry for the inconvenience.
