### ISSUE TITLE
Vitals: SapMachine11: sleep time too long

### ISSUE THREAD

**Issue by tstuefe** [SAP/SapMachine#896]
With the integration of the last vitals changes into SapMachine11 (#820, 0aad4b7a325162248899162258a31a02cd5951dd) an error crept in (SapMachine11 only):

https://github.com/SAP/SapMachine/blob/ca095132d12a9873ad6a791758623a25d71957df/src/hotspot/share/vitals/vitals.cpp#L934

sleep time is too long. `os::sleep()` takes ms, not seconds.

(It is annoying that no regression tests fixed this. I need to write some more tests.)

**Comment by RealCLanger** [comment]
Issue fixed in branch sapmachine11.
