### ISSUE TITLE
sapmachine-11-jre package is no longer available 

### ISSUE THREAD

**Issue by Regloom** [SAP/SapMachine#910]
Hi team,

sapmachine-11-jre package is no longer in "http://dist.sapmachine.io/debian/amd64 ./" repo. 
Could you please assist?

it is used within "https://github.com/cloudfoundry/apt-buildpack" for Cloud Foundry db deployment.

Best regards,
Egor

**Comment by lokhmakov** [comment]
@reshnm Can u help with this?

**Comment by RealCLanger** [comment]
Hi,

the support for JRE packages was removed quite a while ago with this commit to our infrastructure repository: https://github.com/SAP/SapMachine-infrastructure/commit/fc1e96c415a40172a5eb45740adac8c80c69b5fb#diff-688ed9c374901a63dd3f05bb297f2f8739d2161f7feaa3fc180d4705c05cf1e5

So until a few days ago you obviously have used an outdated JRE in your scenario. We have cleaned up our repository now and the old JRE package was removed. At the moment we don't have the intent to resurrect that. What exactly is your case for using it?

Cheers
Christoph

**Comment by lokhmakov** [comment]
@RealCLanger It used during deploy to SAP CAP, PostgreSQL Hyperscaler Option, like this:

https://github.com/gregorwolf/pg-beershop/blob/main/db-deployer-apt/apt.yml

**Comment by RealCLanger** [comment]
And is it impossible to use JDK?

The thing is that JRE is considered legacy and this packaging type shall be removed at all for future Java releases. The idea is to rather prefer custom jlinked runtime images...

**Comment by lokhmakov** [comment]
I think we can try switch to JDK.

**Comment by lokhmakov** [comment]
@RealCLanger Seems sapmachine-11-jdk or java-8-openjdk-amd64 works fine. Thanks.

**Comment by RealCLanger** [comment]
> @RealCLanger Seems sapmachine-11-jdk or java-8-openjdk-amd64 works fine. Thanks.

Perfect. I'm closing this issue then. Thanks for the feedback.

**Comment by valpankaj** [comment]
Hi Experts,

During npx mbt build command, mtar is generated with gen folder having apt.yml, deploy.sh and many others files. Both apt.yml and deploy.sh is having sapmachine-11.jre default config.

how can we change the default config to sapmachine-11.jdk to run our app on SCP?

**Comment by RealCLanger** [comment]
@valpankaj Does this affect an SAP internal build for Cloud Platform? In that case, please send a mail to sapmachine@sap.com and we'll direct you to the appropriate internal support channels.

**Comment by valpankaj** [comment]
@RealCLanger : No. It does not affect the SAP internal Build/ or lets say In general generating .mtar file via npx mbt build.
there generated(Successfully) mtar contains apt.yml and deploy.sh with _sapmachine-11-jre_, So our deployment on SCP is getting failed.
We are expecting mtar with apt.yml and deploy.sh with **sapmachine-11-jdk** which is only possible after cds-dbm version update release.

is there any way to solve this locally or temporary for time being until new version gets available for all.

@lokhmakov  : you valuable inputs will be highly appreciated.

Thanks.
Pankaj V

**Comment by lokhmakov** [comment]
@valpankaj 

Take a look on this: https://github.com/gregorwolf/pg-beershop

Folder `db-deployer-apt`. And in mta.yml u can replace default template folder with it.

**Comment by lokhmakov** [comment]
U can use `sapmachine-11-jre` or `openjdk-8-jre-headless`.

**Comment by RealCLanger** [comment]
> @RealCLanger : No. It does not affect the SAP internal Build/ or lets say In general generating .mtar file via npx mbt build.
> there generated(Successfully) mtar contains apt.yml and deploy.sh with _sapmachine-11-jre_, So our deployment on SCP is getting failed.
> We are expecting mtar with apt.yml and deploy.sh with **sapmachine-11-jdk** which is only possible after cds-dbm version update release.

OK, unfortunately I know nothing about "npx mbt build". Maybe you can share some information (e.g. documentation link) about what that is. Also the term "cds-dbm version update release" is not familiar to me.
