### ISSUE TITLE
Whitesource container scan for sapmachine base image

### ISSUE THREAD

**Issue by santoshkashyap** [SAP/SapMachine#926]
Hi,

In our spring boot application, I tried various version of SapMachine jdk11 as the base docker image. Later when we run whitesource scan as part of OSS checks, I see following vulnerabilities and policy violations for different versions of JDK11:

when used sapmachine:11.0.12 or sapmachine/lts:latest as base image:
Top 5 in the below image are rated high and other medium
![image](https://user-images.githubusercontent.com/16810482/129668241-8ede5213-f965-4abf-a8b5-ed74aa22c0db.png)
 
 Also there is a policy violation for below:
 
![image](https://user-images.githubusercontent.com/16810482/129668444-1536734c-405e-49b6-9841-670ed4005a02.png)

Finally, when tried with older version - sapmachine/jdk11:11.0.2, there are no policy violations, but In total there are 46 vulnerabilities reported for version 11.0.2

Is there a way to mitigate ?

**Best,**
Santosh

**Comment by I521822** [comment]
Hi Team,

We are also facing the issue as described above. We have the vulnerabilities reported in whitesource when using the base image in dockerfile as SapMachine Jdk11.
Please guide as to which version can be used to ensure no license/vulnerability issues for the libraries.

Regards,
Rajat

**Comment by RealCLanger** [comment]
Hi colleagues,

thanks for reporting this issue. As it is about SAP's internal whitesource scans we should not follow up here in public GitHub. Would you mind sending an email to sapmachine@sap.com with reference to this issue?

Thanks & Best regards
Christoph
