### ISSUE TITLE
Cherrypick 8268893: jcmd to trim the glibc heap 

### ISSUE THREAD

**Issue by tstuefe** [SAP/SapMachine#943]
I would like to prematurely downport 8268893: "jcmd to trim the glibc heap" to our older SapMachine releases. Its useful.

I will eventually also downport them upstream to 11u and 17u. But since that one takes a CSR, this will be a lot of red tape to cross, and we need this feature sooner in our VMs.

**Comment by RealCLanger** [comment]
For SapMachine 17 we cherry-picked the change of 17.0.2 into 17.0.1.
For SapMachine11 we did a special downport (99336fe4a6bad60f444a7d5d8b5d4bc1034a2245) as it's unlikely to go into stock OpenJDK 11 Updates.
