### ISSUE TITLE
Print out all flags in hs-err file

### ISSUE THREAD

**Issue by tstuefe** [SAP/SapMachine#950]
In hs-err file, print out all flags, not only the non-default flags.

Traditionally we have done this always, and it simplifies the logistics of error analysis since one does not have to cross-check VM switch default values in the sources.

SAP has always preferred expressive and extensive error reports at the cost of brevity; OpenJDK upstream does not, and therefore I do not believe I would be able to convince folks to do this change upstream. However, the change is super trivial, so it should not be an issue to carry this patch downstream only.

**Comment by RealCLanger** [comment]
We should mention this behavioral difference here when it is integrated: https://github.com/SAP/SapMachine/wiki/Differences-between-SapMachine-and-OpenJDK

**Comment by RealCLanger** [comment]
> We should mention this behavioral difference here when it is integrated: https://github.com/SAP/SapMachine/wiki/Differences-between-SapMachine-and-OpenJDK

I updated the Wikipage. @tstuefe you might want to check...
