### ISSUE TITLE
Vitals: use native lock instead of hotspot Mutex

### ISSUE THREAD

**Issue by tstuefe** [SAP/SapMachine#975]
In the Vitals backend, we synchronize access to the shared sample table via a lock. This is needed since the table is accessed concurrently from two places:
- the sampler thread, when it adds a new sample
- the reporter, when it prints a report.

A report can be triggered from various places: jcmd, VM shutdown, error handling...

Today, we use a hotspot mutex for this synchronization, but since hotspot mutexes are changed upstream (and that work will continue for a while according to @coleenp) I'd like to use native mutexes instead to reduce merging and testing effort. We do not need the additional features hotspot mutexes give us (e.g. deadlock recognition).

**Comment by coleenp** [comment]
On 10/14/21 4:52 AM, Thomas Stuefe wrote:
>
> In the Vitals backend, we synchronize access to the shared sample 
> table via a lock. This is needed since the table is accessed 
> concurrently from two places:
>
>   * the sampler thread, when it adds a new sample
>   * the reporter, when it prints a report.
>
> A report can be triggered from various places: jcmd, VM shutdown, 
> error handling...
>
> Today, we use a hotspot mutex for this synchronization, but since 
> hotspot mutexes are changed upstream (and that work will continue for 
> a while according to @coleenp 
> <https://urldefense.com/v3/__https://github.com/coleenp__;!!ACWV5N9M2RV99hQ!YajnTNeR1Uh09IjCCN_1olIwhBoE5WXEnS3Dy5X464AEX1yz9aIYnFpB1XDAFpJZw6SX8Q$>) 
> I'd like to use native mutexes instead to reduce merging and testing 
> effort. We do not need the additional features hotspot mutexes give us 
> (e.g. deadlock recognition).
>

But why don't you need deadlock recognition and why isn't that helpful?  
I assume these are nosafepoint locks. The Mutex Rank cleanup work is 
mostly done.  I have a couple of small cleanups that I'd like to do, but 
nothing new that would hurt merging.  To backport new changes to old 
releases, it's mostly a substitution of 'nosafepoint' for 'leaf' and I 
think that'll fix things.

The hotspot mutexes aren't really any more heavyweight than that.

Coleen

**Comment by coleenp** [comment]
On 10/14/21 10:13 AM, Thomas Stuefe wrote:
>
>     But why don't you need deadlock recognition and why isn't that
>     helpful?  I assume these are nosafepoint locks. The Mutex Rank
>     cleanup work is mostly done.  I have a couple of small cleanups
>     that I'd like to do, but nothing new that would hurt merging.  To
>     backport new changes to old releases, it's mostly a substitution
>     of 'nosafepoint' for 'leaf' and I think that'll fix things. The
>     hotspot mutexes aren't really any more heavyweight than that. Coleen
>
> Hi Coleen,
>
> thanks for looking into this :)
>
> Vitals are a SapMachine-only feature (which I would love to bring 
> upstream btw but it got rejected, which is a different story). It's 
> always good to keep those patches physically separate from upstream to 
> ease merging. In this case, I had to clean up multiple times after 
> Mutexes changed upstream, so I wanted to use an alternate solution 
> until the dust settles at least.
>
> This mutex is somewhat special in that it may be locked by either a 
> java thread or a non-java thread. The sampler thread is non-java, but 
> the report may be triggered from multiple places, java and non-java 
> threads alike. The lock is a leaf semantically since I do not lock 
> anything below it. I may return to hotspot Mutexes once upstream is 
> stable again.
>

There are several locks that are shared between JavaThreads and 
NonJavaThreads, so that shouldn't be a problem.  You have to specify 
Mutex::_no_safepoint_check flag when taking them out with MutexLocker, 
but that hasn't changed.

I think/hope the dust has settled on the Mutex changes for the most part.

Thanks!
Coleen
