### ISSUE TITLE
Question about SapMachine Java and Floating Point Behaviour.

### ISSUE THREAD

**Issue by PowerUser1234** [SAP/SapMachine#990]
I would like to know how Sapmachine Java performs.

-Is it compatible with Free Open Source Java libraries,
or other Java libraries, out there?

-Has Sapmachine removed the phenomenon of Java
Floating Point denormal and pronormal values?
Consider the following Java code snippet:

**//----------------------------------------------------------
package JavaApplication;
import static java.lang.System.*;
public class Start
{
    public static void main(String ...args)
    {
    out.println("Program has started...");   
    double a = 0.1;   
    double b = 0.1;   
    double c = a*b;   
    out.println();   
    out.println(c);   
    out.println();   
    out.println(c == 0.01);   
    float d = 0.01F; 
    float e = 0.01F;
    float f = d*e;
    out.println();
    out.println(f);
    out.println();
    out.println(f == 0.01);   
    out.println(); 
    out.println("Program has Finished.");
    }}
//----------------------------------------------------------**

-What I need is a version of Java 17 that has the same
free-for-all-use license model as OpenJDK17, but has
removed the phenomenon of denormal and pronormal
values, of all defaulting arithmetic, systematically, 
involving float and double, and their objects.

_-Will Sapmachine run the included code fragment,
outputting the generally expected results, 
printing true and not false?_

**Comment by reinrich** [comment]
Hi @PowerUser1234 
> 
> 
> I would like to know how Sapmachine Java performs.
> 
> -Is it compatible with Free Open Source Java libraries, or other Java libraries, out there?

Running a Java program on SapMachine should yield the same results as running that program on the corresponding upstream version you can find here https://github.com/openjdk. So compatibility should also be the same.

> -Has Sapmachine removed the phenomenon of Java Floating Point denormal and pronormal values? Consider the following Java code snippet:

SapMachine does not differ from the corresponding upstream version in this respect.

> ``` java
> //----------------------------------------------------------
> package JavaApplication;
> import static java.lang.System.*;
> public class Start
> {
> public static void main(String ...args)
> {
> out.println("Program has started...");
> double a = 0.1;
> double b = 0.1;
> double c = a*b;
> out.println();
> out.println(c);
> out.println();
> out.println(c == 0.01);
> float d = 0.01F;
> float e = 0.01F;
> float f = d*e;
> out.println();
> out.println(f);
> out.println();
> out.println(f == 0.01);
> out.println();
> out.println("Program has Finished.");
> }}
> //----------------------------------------------------------
> ```
> 

I had to change your program as follows to make it compile.

``` diff
@@ -1,6 +1,6 @@
 //----------------------------------------------------------
 package JavaApplication;
-import static java.lang.System.;
+import static java.lang.System.*;
 public class Start
 {
 public static void main(String ...args)
@@ -8,7 +8,7 @@
 out.println("Program has started...");
 double a = 0.1;
 double b = 0.1;
-double c = ab;
+double c = a*b;
 out.println();
 out.println(c);
 out.println();
```

> 
> -What I need is a version of Java 17 that has the same free-for-all-use license model as OpenJDK17, but has removed the phenomenon of denormal and pronormal values, of all defaulting arithmetic, systematically, involving float and double, and their objects.
> 
> _-Will Sapmachine run the included code fragment, outputting the generally expected results, printing true and not false?_

This is the output when running your program on SapMachine.

```
Program has started...

0.010000000000000002

false

1.0E-4

false

Program has Finished.
```

This is very unlikely to change in future versions I'm afraid.

You might want to look at [BigDecimal](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/BigDecimal.html) though. It might suite your needs.

For example

``` java
//----------------------------------------------------------
package JavaApplication;
import static java.lang.System.*;
import java.math.BigDecimal;
public class Start
{
public static void main(String ...args)
{
out.println("Program has started...");
BigDecimal a = new BigDecimal("0.1");
BigDecimal b = new BigDecimal("0.1");
BigDecimal c = a.multiply(b);
out.println();
out.println(c);
out.println();
out.println(c.equals(new BigDecimal("0.01")));
out.println("Program has Finished.");
}}
//----------------------------------------------------------
```

prints

```
Program has started...

0.01

true
Program has Finished.
```

Hope this helps a little bit.
