### ISSUE TITLE
SAP GUI 770 Always exit unexpectedly

### ISSUE THREAD

**Issue by leialbert** [SAP/SapMachine#991]
I was using the 

> SAP GUI for Java 7.70 rev 3
> (Version ID 077000040300)
> 2021-08-05 08:57:00 +0200
> gclm0108, 760_REL, 2082961
> Java VM: SAP SE Version 11.0.12+7-LTS-sapmachine
> OS: Mac OS X(x86_64) Version 12.0.1

The SAP GUI Always exit unexpectedly, I don't know why. And the error log is showing a fatal error has been detected by the Java Runtime Environment:(Here is the error log)

[hs_err_pid12819.log](https://github.com/SAP/SapMachine/files/7576045/hs_err_pid12819.log)
[hs_err_pid16938.log](https://github.com/SAP/SapMachine/files/7576046/hs_err_pid16938.log)

Please if anyone can tell me how to fix the bug!

Thank you so much.

**Comment by leialbert** [comment]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/46070462/142769951-b3fcdb22-328f-4a9b-98d9-7fedec73879f.png">

Why this happened so frequently?

**Comment by reinrich** [comment]
Hi Albert,

this looks like an instance of the following bug [JDK-8275723: Crash on macOS 12 in GlassRunnable::dealloc](https://bugs.openjdk.java.net/browse/JDK-8275723).

The good news is that the bug is fixed already and it was also downported to openjdk 11.0.14 which is the next release.

Cheers, Richard.

**Comment by leialbert** [comment]
> Hi Albert,
> 
> this looks like an instance of the following bug [JDK-8275723: Crash on macOS 12 in GlassRunnable::dealloc](https://bugs.openjdk.java.net/browse/JDK-8275723).
> 
> The good news is that the bug is fixed already and it was also downported to openjdk 11.0.14 which is the next release.
> 
> Cheers, Richard.

Hi, rein rich,  Do you mean that I should update my java version to the openjdk 11.0.14 ?
Thanks.

**Comment by reinrich** [comment]
I recommend updating to SapMachine 11.0.14.
But you have to wait for it to be released shortly after January 18.
SapMachine follows closely the [release schedule of OpenJDK Updates](https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u).

Cheers, Richard.

**Comment by RealCLanger** [comment]
Hi,
no, the fix is in OpenJFX. I've contacted SAP GUI folks to give you some directions. I think they have some hotfix or so...
Cheers
Christoph

**Comment by leialbert** [comment]
> Hi,
> no, the fix is in OpenJFX. I've contacted SAP GUI folks to give you some directions. I think they have some hotfix or so...
> Cheers
> Christoph

Hi, Christoph
I don't have too much knowledge on JAVA , please share me some directions for how to update the OpenJFX for SAP Machine, this issue affects the work very much.
Thank you for your help.

Br,
Albert

**Comment by leialbert** [comment]
> I recommend updating to SapMachine 11.0.14. But you have to wait for it to be released shortly after January 18. SapMachine follows closely the [release schedule of OpenJDK Updates](https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u).
> 
> Cheers, Richard.

Thanks, Richard, as Christoph replied to me too , I will try his solution if possible. please or can you find that if there is any way to solve the issue right now?
Br,
Albert

**Comment by woersi** [comment]
Hello Albert,

This is a known issue as described in [SAP note 3113183](https://launchpad.support.sap.com/#/notes/3113183) .

If you open a support incident at SAP on component BC-FES-JAV for this bug, we can provide you an intermediate version of SAP GUI for Java containing the new OpenJFX version which is addressing that issue.

Best regards
Rolf-Martin

**Comment by leialbert** [comment]
> Hello Albert,
> 
> This is a known issue as described in [SAP note 3113183](https://launchpad.support.sap.com/#/notes/3113183) .
> 
> If you open a support incident at SAP on component BC-FES-JAV for this bug, we can provide you an intermediate version of SAP GUI for Java containing the new OpenJFX version which is addressing that issue.
> 
> Best regards Rolf-Martin

Hi, Martin, I checked the note you shared , By the way,  how can I open a support at SAP on component BC-FES-JAV?
<img width="1170" alt="20211122-112809@2x" src="https://user-images.githubusercontent.com/46070462/142828069-20ea9c77-e7ce-41ae-a3c7-063b98899b41.png">
 
Thanks
Br,
Albert

**Comment by woersi** [comment]
Hello Albert, Please refer to [SAP note 1296527](https://launchpad.support.sap.com/#/notes/1296527) how to open a support incident.
Best regards
Rolf-Martin

**Comment by RealCLanger** [comment]
Hi,
thanks @woersi for pointing @leialbert the direction. With that I'm closing this issue now but it should still be possible to post here if you have follow up questions.
Cheers
Christoph

**Comment by ryanmsnyder** [comment]
@leialbert did you ever find a solution? I've been dealing with the same issue on M1.
